Create architectures and components when creating a release
pulp/pulp_deb pull request #1069
Opened 2024-04-19 18:50 UTC by adrianabedon

This PR adds the following: 
1. Allows for a single api call to create release, components, and architectures. 
2. Adds retrieve functionality to the release creation endpoint. If a release already exists, then the existing release will be retrieved. 
3. The release creation endpoint did not originally return a task, which is a bug since it can add content to a repository. This PR updates the endpoint to return a task.

closes #1038

2024-04-22 06:52 UTC, mdellweg commented on pulp_deb/app/serializers/content_serializers.py
> +            CreatedResource(content_object=content).save()
```suggestion
        if created:
            CreatedResource(content_object=content).save()
        else:
            content.touch()
```
We may need to protect this from cleanup.

2024-04-22 11:50 UTC, daviddavis commented
The docs test failure is from this script in the docs which is expecting the release endpoint to return a release object instead of a task:

https://github.com/pulp/pulp_deb/blob/3a0ef81f6cbf876abdaf53559a3d96c7010485b9/docs/_scripts/structured_repo.sh#L34

This script is on this page:

https://docs.pulpproject.org/pulp_deb/workflows/upload.html#create-a-structured-repo-manually

2024-04-22 11:51 UTC, daviddavis commented
With your change, these lines shouldn't even be needed anymore:

https://github.com/pulp/pulp_deb/blob/3a0ef81f6cbf876abdaf53559a3d96c7010485b9/docs/_scripts/structured_repo.sh#L37C1-L39C1

2024-04-23 12:17 UTC, quba42 commented on CHANGES/1038.feature
> +Create architectures and components with a release and return a task when creating a release
Very minor request: Could you configure your text editor to add a final trailing newline `\n` at the end of the file?

I don't think this really matters for anything, other than that it bothers my sense of order in the universe. :sweat_smile:

2024-04-24 05:46 UTC, quba42 commented
@daviddavis So, since we are adding retrieve functionality (changing API behavior), if we were to adhere to semantic versioning, then we would need to call the next release after merging this 4.0.0, right?

Maybe I have wrong associations regarding X version bumps, but this feels wrong to me. I feel like an X version bump also creates the expectation that this is some kind of major release with many new features (rather than one small feature that happens to change some API behavior).

@mdellweg Do you have an opinion or intuition on this?

2024-04-24 05:51 UTC, quba42 commented
Regarding the failed docs test, this should turn green once https://github.com/pulp/pulp_deb/pull/1074 is merged (and this PR rebased on top of it).

2024-04-24 11:13 UTC, mdellweg commented
> @daviddavis So, since we are adding retrieve functionality (changing API behavior), if we were to adhere to semantic versioning, then we would need to call the next release after merging this 4.0.0, right?
> 
> Maybe I have wrong associations regarding X version bumps, but this feels wrong to me. I feel like an X version bump also creates the expectation that this is some kind of major release with many new features (rather than one small feature that happens to change some API behavior).
> 
> @mdellweg Do you have an opinion or intuition on this?

I'm not an expert here. To some extend every change you do (even just bugfixes) are changing some behaviour. That's why we call it software. Because it is not completely rigid. Even "just" adding a new endpoint is normally not considered a breaking change, but if you had someone relying on /api/foo/ returning 404 you'd break them. I think it's really hard to tell where to draw the line.
In particular, adding the retrieve functionality is like stopping to return an error condition and actually doing what the user intended the server to do. Is this a breaking change? I'd say no.

2024-04-24 11:16 UTC, mdellweg commented
Having said all that, semver is not about "big changes", but only about "did you break a user?". OTOH I believe semver is designed for shared libraries. Applying it to a REST API is already quite a stretch.

2024-04-24 23:45 UTC, adrianabedon commented
I went ahead and added a test case to the PR.

2024-04-25 16:18 UTC, daviddavis commented on docs/_scripts/structured_repo.sh
> +TASK_HREF=$(http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} distribution=${DIST} ${RELEASE_FILE_FIELDS[@]} | jq -r .pulp_href)
```suggestion
TASK_HREF=$(http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} distribution=${DIST} ${RELEASE_FILE_FIELDS[@]} | jq -r .task)
```

2024-04-25 17:22 UTC, adrianabedon commented on docs/_scripts/structured_repo.sh
> +TASK_HREF=$(http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} distribution=${DIST} ${RELEASE_FILE_FIELDS[@]} | jq -r .pulp_href)
Good catch

2024-05-06 09:25 UTC, quba42 requested changes
The code changes and test look good to me. My only suggestions relate to changelog and documentation. I will try my best to test this later today. Should fit well with some Pulp CLI work I need to do.

My apologies for the delays in getting this review written down.

2024-05-06 13:53 UTC, quba42 commented
I just tested using something like the following workflow:
```
NAME='empty-metadata-repo'
REPO_HREF=$(pulp deb repository create --name=${NAME} | jq -r '.pulp_href')

RELEASE_OPTIONS=(
  distribution=custom
  codename=custom
  suite=stable
  version=1
  origin=myorigin
  label=mylabel
  description=mydescription
)

http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} architectures:='["amd64", "i386"]' components:='["main", "contrib", "non-free"]' "${RELEASE_OPTIONS[@]}"

pulp deb publication create --repository=${NAME}
pulp deb distribution create --name=${NAME} --base-path=${NAME} --repository=${NAME}
```
I then went and destroyed the repo again and re-added the release with only some of the components and architectures, adding the rest in a separate second API call. I noticed the following slightly odd behavior:

- The Release will always be listed in the `created_resources` of the task (regardless of whether it already exists in Pulp or not).
- Any relevant ReleaseComponents and ReleaseArchitectures will be listed in the `created_resources` of the task only if they were actually created by the API call. If they already existed within Pulp and were retrieved, they are still added to any resultant new repository version, but they are not listed in `created_resources`.

I believe this is undesirable since (in the future when we have RBAC) we don't want to leak any information about what ReleaseComponents and ReleaseArchitectures already exist within Pulp. So Ideally they should always be listed in `created_resources` irrespective of whether they already existed or were just created. Just like the Release.

To achieve this we probably need to update the task manually when we go through the retrieve case. That being said, I am not sure how easy it is to access the task, given it is created by pulpcore, and not by us.

I think we already have the same wonky behavior when uploading packages as well, so we could leave this for a follow up PR.

2024-05-06 14:52 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +            content.touch()
@mdellweg I believe we do want to always list all relevant entities in `created_resources`, regardless of whether they were in fact created or retrieved. Is that correct? Just want to confirm with you.

2024-05-07 21:06 UTC, adrianabedon commented on CHANGES/1038.feature
> +Create architectures and components with a release and return a task when creating a release
I applied these suggestions to the changelog

2024-05-07 21:21 UTC, adrianabedon commented on docs/_scripts/structured_repo.sh
> +TASK_HREF=$(http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} distribution=${DIST} ${RELEASE_FILE_FIELDS[@]} | jq -r .task)
I changed the script to create a Release with architectures and the components before uploading the package.

2024-05-07 21:29 UTC, adrianabedon commented on pulp_deb/app/serializers/content_serializers.py
> +            content.touch()
I implemented the suggestion. I wasn't sure what the correct behavior was when originally making changes. I was basing the logic off of the package upload serializer which has a [similar function](https://github.com/pulp/pulp_deb/blob/3699b9f97ea75b06ebdcd465345c47847e20f8a3/pulp_deb/app/serializers/content_serializers.py#L250C5-L254C60).

2024-05-08 08:41 UTC, mdellweg commented on pulp_deb/app/serializers/content_serializers.py
> +            content.touch()
I don't know the right way to do it.

2024-05-08 15:19 UTC, daviddavis approved these changes

2024-05-08 15:23 UTC, daviddavis commented on docs/_scripts/structured_repo.sh
> +TASK_HREF=$(http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} distribution=${DIST} ${RELEASE_FILE_FIELDS[@]} architectures:=\'["amd64", "ppc64"]\' components:=\'["${COMP}"]\'
I think there is something wrong with this line that's causing the docs CI job to fail.

2024-05-08 16:49 UTC, quba42 commented on docs/_scripts/structured_repo.sh
> +TASK_HREF=$(http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} distribution=${DIST} ${RELEASE_FILE_FIELDS[@]} architectures:=\'["amd64", "ppc64"]\' components:=\'["${COMP}"]\'
From the error:
```
error:
    argument REQUEST_ITEM: "ppc64]'" is not a valid value
```
It looks like the escapes for `architectures:=\'["amd64", "ppc64"]\'` are not quite right. Since there is no bash variable in there, maybe the `'` does not need to be escaped? Or maybe the `[` and `]` do need to be escaped? Welcome to bash escape hell!

2024-05-08 16:54 UTC, quba42 commented on CHANGES/1038.feature
> +Also added retrieve functionality to the release API.
Really minor nitpick, but I recommend configuring your text editor to add final trailing newline characters at the end of files. Most places want a trailing newline at the end of the file. And for most editors it is easy to configure this behavior once and then never have to think about it again.

`CHANGES/1038.removal` below also lacks the trailing newline.

2024-05-08 22:02 UTC, adrianabedon commented on CHANGES/1038.feature
> +Also added retrieve functionality to the release API.
I added the newlines. I'll remember this for future contributions!

2024-05-08 22:03 UTC, adrianabedon commented on docs/_scripts/structured_repo.sh
> +TASK_HREF=$(http ${PULP_URL}/pulp/api/v3/content/deb/releases/ repository=${REPO_HREF} distribution=${DIST} ${RELEASE_FILE_FIELDS[@]} architectures:=\'["amd64", "ppc64"]\' components:=\'["${COMP}"]\'
I definitely confused myself with the escape characters. Everything should be working now.

2024-05-09 16:21 UTC, daviddavis approved these changes

2024-06-05 11:00 UTC, quba42 approved these changes
Had one final look over the latest state and re-tested my workflow. => LGTM!

Also tested that I can make the test fail by deliberately breaking the code. => check!

Thanks for the good work, and being patient while waiting for my reviews.

2024-06-05 11:01 UTC, merged