Fixed PRC not getting removed when modifying repositories
pulp/pulp_deb pull request #1185
Opened 2024-11-14 15:33 UTC by hstct

closes #1190

2024-11-14 15:46 UTC, quba42 commented on pulp_deb/app/viewsets/repository.py
> +        matching_components = PackageReleaseComponent.objects.filter(package__in=matching_packages)
I am wondering if we should scope this to just PRC that are in the relevant repository version.
That being said, unless removal of an href that is not in the version produces an error I don't see any issue with simply removing _all_ PRC that exists for the package in question.

2024-11-20 14:00 UTC, quba42 commented on pulp_deb/app/viewsets/repository.py
> +        matching_components = PackageReleaseComponent.objects.filter(package__in=matching_packages)
I tested this and it does not appear to hurt.

2024-11-20 14:30 UTC, quba42 requested changes
I only have some small suggestions. Even without the everything appears to work.

I manually tested the following:
```
workon pulp_cli
alias pulp='pulp -p oci-env'
NAME='package_removal_test'

alias http='http --auth admin:password '
PULP_URL='http://localhost:5001'

pulp status
http get ${PULP_URL}/pulp/api/v3/status/


pulp deb repository create --name="${NAME}"
pulp deb content upload --file='../neovim_0.3.4-3_amd64.deb' --distribution='my-dist' --component='my-component' --repository="${NAME}"
pulp deb content upload --file='../odin_1.0_ppc64.deb' --distribution='my-dist' --component='my-component' --repository="${NAME}"

pulp deb repository create --name="${NAME}2"
pulp deb content upload --file='../neovim_0.3.4-3_amd64.deb' --distribution='my-dist2' --component='my-component2' --repository="${NAME}2"

pulp deb publication create --repository=${NAME}
pulp deb distribution create --name=${NAME} --base-path=${NAME} --repository=${NAME}


REPOSITORY_HREF=$(pulp deb repository show --name=${NAME} | jq -r .pulp_href)
PACKAGE_HREF=$(pulp deb content show --sha256='e36dccccd1fd8e38086b15d81d9aef049bc0586dd9b540b171d6917e41268f61' | jq -r .pulp_href)
TASK_HREF=$(http post ${PULP_URL}${REPOSITORY_HREF}modify/ remove_content_units:=[\"${PACKAGE_HREF}\"] | jq -r .task)
pulp show --href=${TASK_HREF}
```
This ensures that PRCs that point to the same package, but are not part of the repo we are removing from are not a problem.

I also tested removing multiple packages in a single API call, which worked fine.

2024-11-20 14:30 UTC, quba42 commented on CHANGES/1190.bugfix
> +Packages removed via the repository modify API endpoint now also have their associated Package Release Components removed if they reference the package hrefs.
```suggestion
Removing packages from a repository using the modify API endpoint now also removes all associated PackageReleaseComponents.
```

2024-11-20 14:30 UTC, quba42 commented on pulp_deb/app/viewsets/repository.py
> +        return prc_href
Naming nitpicks:
```suggestion
        matching_prcs = PackageReleaseComponent.objects.filter(package__in=matching_packages)
        prc_hrefs = [get_url(prc) for prc in matching_prcs]
        return prc_hrefs
```
Because the name `components` makes me think of the `ReleaseComponent` class, not the `PackageReleaseComponent` class.

2024-11-20 14:30 UTC, quba42 commented on pulp_deb/tests/functional/api/test_publish.py
> +    repo = deb_get_repository_by_href(repo.pulp_href)
This is needed to make repo update its latest_version_href, etc.?

2024-11-20 14:30 UTC, quba42 commented on pulp_deb/tests/functional/api/test_publish.py
> +    assert not any(package.pulp_href == prc.package for prc in prcs)
This assertion seems redundant given we are also asserting `len(prcs) == 0`?

Should we drop it?

2024-11-20 15:33 UTC, hstct commented on pulp_deb/tests/functional/api/test_publish.py
> +    repo = deb_get_repository_by_href(repo.pulp_href)
eh I don't think it's strictly needed if you are referring to the `base_version` ?

2024-11-20 16:10 UTC, quba42 approved these changes
LGTM.

2024-11-21 08:02 UTC, merged