Support flat repo format
pulp/pulp_deb pull request #225
Opened 2020-10-15 10:15 UTC by ThikaXer

fixes #7502
https://pulp.plan.io/issues/7502

2020-10-15 10:40 UTC, quba42 commented
The following is a check list for what needs to happen before this PR is fully ready:

- [ ] Provide the requested functionality
- [ ] Add a flat repository format fixture to https://github.com/pulp/pulp-fixtures
- [ ] Use the new fixture for a full sync + publish + distribute test (there should be existing tests that do this for the existing fixtures that can be emulated).
- [ ] Add this new feature to the feature overview documentation.
- [ ] Update the documentation for how users should set the `distribution` field in their remotes (both API and workflow docs). We should explicitly mention that this field uses the same syntax as `/etc/apt/sources.list` entries.

2020-10-29 17:50 UTC, digger18 commented
Any update on this PR?
Thanks in advance!

2020-10-29 17:52 UTC, snirkatriel commented
+1 👆

2020-10-29 17:57 UTC, ThikaXer commented
Fixtures have been created in https://github.com/pulp/pulp-fixtures/pull/199 but have not yet been merged (that's why Travis not yet running through I think). Quba42 is on holiday this week and thus not reviewing.
Test has already been included in test_publish_flat_repo_format.py
I'm not that sure where in the documentation I need to mention this feature...

2020-10-29 17:59 UTC, ThikaXer commented
I would appreciate any reccomendation on or reviews of the code, as I'm still very new to this! Thanks in advance :)

2020-10-30 15:18 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +        log.info('Parsing Release file for distribution: "{}"'.format(distribution))
```suggestion
        log.info('Parsing Release file for release: "{}" at distribution: "{}"'.format(release_file.codename, distribution))
```
You never know which information might be really needed in the logfiles...

2020-10-30 15:19 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +        if self.distributions[0][-1] == "/":
Maybe add the "flat repo" comment here too.

2020-10-30 15:20 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +            package_index_dir = ""
I guess, those "flat repos" only support "*.deb" and not "*.udeb"?

2020-10-30 15:21 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_publish_flat_repo_format.py
> +            "release_file_folder_dist": "dists/debian-flat/",
This is because we republish them "not flat"?

2020-11-02 13:04 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +            package_index_dir = ""
Hm, I'm not sure, it's not specified anywhere (here the definition from debian flat repos https://wiki.debian.org/DebianRepository/Format#Flat_Repository_Format ). I would assume that *.udebs should be ssupported as well, but still they will be just in the same directory as everything else... What do you think?

2020-11-02 13:11 UTC, ThikaXer commented on pulp_deb/tests/functional/api/test_publish_flat_repo_format.py
> +            "release_file_folder_dist": "dists/debian-flat/",
Here, I was not sure how to proceed. Maybe you have some suggestions or ideas.
the problem is, that on one side, structured publishing should look more or less like the original (as I understand it). Here, we get a conflict with the style of where Release file and Packages files are: in structured we want to introduce the architecture all if not yet there. So for flat repositories how should one do that? 
On the other side, having some structured repository (ie folder structure in dists/ and pool/) is quite nice, too, maybe even nicer than just putting everything in one directory as the flat repo does. 
So in the end, I left the structured publisher to do a "structured" but not flat publishing. If one really wants to keep the flat structure, the verbatim publisher can be used.

What do you think about this problem?

2020-11-02 13:17 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +        if self.distributions[0][-1] == "/":
Done.

2020-11-02 13:17 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +        log.info('Parsing Release file for distribution: "{}"'.format(distribution))
Done.

2020-11-02 13:22 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_publish_flat_repo_format.py
> +            "release_file_folder_dist": "dists/debian-flat/",
I was asking to understand. If you use the structured publishing, it should be structured (as in looking as if it were an official upstream debian repository with different packages).
There is no need to try to mimic the structure of how the repository was synced if you need to republish anyway.
Verbatim is really for creating a bit by bit identical mirror that is preserving valid signatures on the metadata.

2020-11-02 14:41 UTC, ThikaXer commented on pulp_deb/tests/functional/api/test_publish_flat_repo_format.py
> +            "release_file_folder_dist": "dists/debian-flat/",
Ah, then this should be ok, shouldn't it?

2020-11-02 14:56 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_publish_flat_repo_format.py
> +            "release_file_folder_dist": "dists/debian-flat/",
Yes. Sorry if i confused you.

2020-11-02 16:16 UTC, ThikaXer commented on pulp_deb/tests/functional/api/test_publish_flat_repo_format.py
> +            "release_file_folder_dist": "dists/debian-flat/",
No prob, thanks for the input ;)

2020-11-09 14:03 UTC, digger18 commented
Can this be merged? we need it :)

2020-11-17 09:34 UTC, quba42 commented
> Can this be merged? we need it :)

I will start final review now. I think there is a good chance this will be merged this week. I plan to create a release as soon as this is merged. The next release will have version 2.8.0 and is needed anyway before pulpcore 3.9.0 is released at the end of the month.

2020-11-17 10:20 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +            package_index_dir = ""
A Debian repo in flat repo format supports at most a single `Packages` and a single `Sources` index. Unless it is possible to reference a mix of both `.deb` and `.udeb` packages from a single `Packages` file (I don't think so?!) it is therefore not possible to have `.udeb` packages? Or maybe it is possible to have a flat repo format repo containing exclusively `.udeb` packages?

Anyway, from a practical point of view, I think we can shelve this discussion. If anyone ever finds a flat repo with `.udeb` packages in the wild, they can open a new issue then. For now, I say the `pulp_deb` plugin supports `.deb` packages only for flat repos. Most people who are expert enough to create installer packages, are probably also expert enough to use full repo structure...

2020-11-18 13:27 UTC, quba42 requested changes
So, I am unsure if we want to permit users giving a distribution starting with `./`.
I am also not entirely sure if it makes sense for us to create release component content units during the sync of the flat repo case. (I guess we could argue that flat repos implicitly have a single component, and this would have the advantage that the structured publisher will be able to publish flat repos.)

I would also like to add some more documentation. (If you don't mind I can do that, and then you can review it.)

2020-11-18 13:27 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +                package_relpath = os.path.normpath(package_paragraph["Filename"])
Just tested out this function on various examples.
This is a pretty useful function that we might use in place of some of our `strip` functions as well. (Although it might not do exactly what we want in all cases).

2020-11-18 14:43 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +            package_index_dir = ""
Here, I think  it really should be just the empty string as the Packages file is referenced relative to the Release file, isn't it? I just tested with the `package_index_dir = release_file.distribution.strip("/")` but it could not locate the Packages file. I tested it locally with the `nest/fjalar/` distribution but removed the Packages files in the root.

2020-11-18 14:45 UTC, ThikaXer commented on CHANGES/7502.feature
> +Support flat repository format
Done

2020-11-18 14:46 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +        if distribution == "/" or distribution == "./":
Done

2020-11-18 14:46 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +            'Parsing Release file for release: "{}" at distribution: "{}"'.format(
Done

2020-11-18 14:46 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +        if self.distributions[0][-1] == "/":
Done

2020-11-18 14:46 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +            # in case te repo is in flat repo format leave out the dir
Done

2020-11-18 14:46 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +            # "dists/infix/binary-architecture"
Done

2020-11-18 15:38 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +            package_index_dir = ""
You are right, these are the paths as found in the Release file, not the paths relative to the repo root. My bad!

2020-11-18 15:45 UTC, quba42 requested changes
Two more strip corrections and then we should be able to merge. (At least I think those should be changed?)

2020-11-18 15:45 UTC, quba42 commented on pulp_deb/app/tasks/publishing.py
> +                self.parent.distribution.strip("./"),
```suggestion
                self.parent.distribution.strip("/"),
```

2020-11-18 15:45 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +            release_file_dir = distribution.strip(".")
```suggestion
            release_file_dir = distribution.strip("/")
```

2020-11-18 15:54 UTC, ThikaXer commented on pulp_deb/app/tasks/publishing.py
> +                self.parent.distribution.strip("./"),
Done

2020-11-18 15:54 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +            release_file_dir = distribution.strip(".")
Done

2020-11-18 15:55 UTC, quba42 approved these changes

2020-11-18 15:58 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +            release_file_dir = distribution.strip(".")
I think we can even reduce the code a bit more. With strip() we have the possibility to combine both cases of flat repo format

2020-11-19 13:15 UTC, merged