Ignore architectures with missing Packages file
pulp/pulp_deb pull request #226
Opened 2020-10-30 09:35 UTC by ThikaXer

fixes #7467

2020-10-30 12:57 UTC, mdellweg requested changes

2020-10-30 12:57 UTC, mdellweg commented on CHANGES/7467.feature
> +Allows pulp_deb to synchronise a repository with missing architectures, ie in the Release file architectures are specified but the corresponding Packages files are missing.
Changes should be formulated in past tense.
This line is what will be compiled into the changelog.

2020-10-30 12:57 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +from urllib.request import urlopen
you should use aio* libraries in the sync code.
Especially for things that may stall the event loop.

2020-10-30 14:05 UTC, ThikaXer commented on CHANGES/7467.feature
> +Allows pulp_deb to synchronise a repository with missing architectures, ie in the Release file architectures are specified but the corresponding Packages files are missing.
Fixed.

2020-11-02 16:15 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +from urllib.request import urlopen
I tried to understand the async and the aiohttp library, but somehow I seem to miss something (or everything). How can I know in which ClientSession I'm in for example? I need a ClientSession to do a request to a website, don't I?
Or is it ok to say the following?
```
async def download():
   Do the urllib.request here

Later in synchronize:
task = asyncio.create_task(download())
await task
´´´
Maybe this just pushing the problem along?

2020-11-03 07:31 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +from urllib.request import urlopen
Yes, this is still the same problem. This whole sync pipeline is written in async python [0]. That means the code should not incorporate any blocking call ever. Downloader that are safe to use as a coroutine are described in [1].

[0] https://docs.python.org/3/library/asyncio.html
[1] https://docs.pulpproject.org/pulpcore/plugins/api-reference/download.html#parallel-downloading

2020-11-03 14:53 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +from urllib.request import urlopen
Thanks! I tried again with asyncio... it took me quite a while to understand where the problem is. Is the new version better?

2020-11-04 09:26 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +from urllib.request import urlopen
With respect to not using requests, definitely. Somehow i have the impression this should be a lot less complex to implement. Trying to understand that piece of code once more:
You see there is the `NoPackageIndexFile` exception that is emitted in two places in `DebUpdatePackageIndexAttributes`. This is the places the code already knows about the condition you are after. And given the asynchronous nature of that code i'd suggest you try to recover from there by catching the exception, resolving the `d_content' to `None`, and then (back in the first stage) ignoring the futures that resolved to `None`.

2020-11-04 09:45 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +from urllib.request import urlopen
Maybe you even want to make the reaction to those missing files configurable.

2020-11-09 16:41 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +                        with NamedTemporaryFile(delete=False) as temp_file:
I don't think you should replace it with an empty file. Rather just resolve the d_content to None and don't even send it down to the next pipeline step.

2020-11-10 10:23 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +                        d_content = None
When setting d_content to None and later in DebFirstStage (533-535)
```
        if package_index.main_artifact.file.size == 0: #no package_index
            log.info("PackageIndex created but was None")
            return
```
the program seems to run in a non ending loop. How can I find out where the problem is this time?

2020-11-10 10:43 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +                        d_content = None
if think it is 
```
d_content.content = None
d_content.resolve()
```

The pipeline is heavily using this pattern:
https://docs.pulpproject.org/pulpcore/plugins/api-reference/stages.html#pulpcore.plugin.stages.ResolveContentFutures

2020-11-10 10:48 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +                        d_content = None
So i think the best way to handle this is
1. start from scratch
2. replace the `raise NoPackageIndexFile(relative_dir=relative_dir)` with
```
d_content.content = None
d_content.resolve()
continue
```
3. handle the None case in the first stage
4. consider an option to decide about failing or ignoring

2020-11-10 15:02 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +                        d_content = None
Thanks! Here is the next try ;)
Right now, I only included steps 1-3. Concerning step 4, I would have to think a bit more about where to let the user set the handle of failing or ignoring.

2020-11-10 16:14 UTC, mdellweg commented on CHANGES/7467.feature
> +Allowed pulp_deb to synchronise a repository with missing architectures, ie in the Release file architectures are specified but the corresponding Packages files are missing.
I think, a missing Packages file is indicating, that a combination of component-architecture is missing.

2020-11-10 16:14 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +                        continue
:+1:
Sorry, it should have been more obvious to me in the first place.

2020-11-11 08:36 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +                        continue
No problem. I missed the d_content.resolve() and got confused :)

2020-11-11 08:41 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +                        with NamedTemporaryFile(delete=False) as temp_file:
Done.

2020-11-11 09:15 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +                        continue
Yeah, i just saw that https://docs.pulpproject.org/pulpcore/plugins/plugin-writer/concepts/sync_pipeline/sync_pipeline.html#multiple-level-discovery and https://docs.pulpproject.org/pulpcore/plugins/api-reference/stages.html#pulpcore.plugin.stages.ResolveContentFutures may not be enough to under stand that pattern.

Given your recent insight into the "looping pattern" of the stages api. Would you be willing to improve the documentation there? Add some cross references and start a paragraph with "If you need to drop DeclarativeContent prematurely from the pipeline...".

2020-11-11 09:21 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_sync.py
> -
I am still not entirely convinced that this is covering all usecases. If i specify, that i want to sync a set of components with a set of architectures, and one of the combinations is missing i might consider that an error.
Should we have an option on the remote to switch this between warning and failing?
@quba42 Any thoughts?

2020-11-11 09:24 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +    monitor_task,
There is a (maybe better) version of this tool in pulp-smash.pulp3.bindings now.
You should probably migrate that eventually. (Not this PR)

2020-11-11 09:27 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +        self.assertIsNotNone(repo.latest_version_href)
latest version will never be none, be cause an empty repository will still have version 0.
So this assertion does not help anything.

2020-11-11 09:32 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +            self.assertIn(component["component"], expected_values["components"])
This looks like a set comparison (`set(...) == set(...)`)

2020-11-11 09:34 UTC, mdellweg commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +        package_indecies = get_content(
Typo: indices

2020-11-11 10:36 UTC, ThikaXer commented on CHANGES/7467.feature
> +Allowed pulp_deb to synchronise a repository with missing architectures, ie in the Release file architectures are specified but the corresponding Packages files are missing.
Done.

2020-11-11 12:42 UTC, quba42 commented on CHANGES/7467.feature
> +Allowed pulp_deb to synchronize a repository with missing Packages file for a architecture-component combination, even though it is specified in the Release file.
Since we are now planning to make it configurable per remote flag, I would suggest something like:
```suggestion
Users may set the ``ignore_missing_package_indices`` flag in their remotes, to allow the synchronization of repositories missing declared package indices.
```

2020-11-11 13:51 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +from urllib.request import urlopen
Done.

2020-11-11 13:52 UTC, ThikaXer commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +        self.assertIsNotNone(repo.latest_version_href)
Done.

2020-11-11 13:53 UTC, ThikaXer commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +            self.assertIn(component["component"], expected_values["components"])
It is now handled in a better way, I hope ;) Done

2020-11-11 13:53 UTC, ThikaXer commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +        package_indecies = get_content(
Done

2020-11-11 13:53 UTC, ThikaXer commented on CHANGES/7467.feature
> +Allowed pulp_deb to synchronize a repository with missing Packages file for a architecture-component combination, even though it is specified in the Release file.
Done

2020-11-11 16:07 UTC, mdellweg commented on CHANGES/7467.feature
> +Users may set the ``ignore_missing_package_indices`` flag in their remotes, to allow for the synchronization of repositories missing declared package indices.
This should still be worded as a change.
Maybe: "Added an ``ignore_missing_package_indices`` flag to remotes, so users may..."

2020-11-16 12:30 UTC, ThikaXer commented on CHANGES/7467.feature
> +Users may set the ``ignore_missing_package_indices`` flag in their remotes, to allow for the synchronization of repositories missing declared package indices.
Done. I rewrote the changes sentence :)

2020-11-16 12:33 UTC, ThikaXer commented on pulp_deb/tests/functional/api/test_sync.py
> -
Reverted this.

2020-11-16 12:35 UTC, quba42 commented on pulp_deb/tests/functional/api/test_sync_missing_architecture.py
> +    monitor_task,
Should I open an issue for that? Something like "Replace pulp_deb.tests.functional.utils.monitor_task with tool from pulp-smash.pulp3.bindings for tests"?

2020-11-16 12:39 UTC, quba42 commented on pulp_deb/app/serializers/remote_serializers.py
> +        'Set this flag to allow the synchronization of such "partial mirrors" '
Should this be "set this flag to True", or is it obvious that "setting a flag" means "setting it to True"?

2020-11-16 13:02 UTC, quba42 requested changes
Looks very nearly done to me. I will merge as soon as the last few open threads are resolved.

2020-11-16 13:02 UTC, quba42 commented on pulp_deb/app/serializers/remote_serializers.py
> +        help_text="By default, upstream repositories that declare architectures "
I will double check and report back whether literal newlines in the `help_text` will result in the desired output for the auto generated API docs.

We will also need to remember to update `docs/_static/api.json` (hopefully for the last time) with the next release.

2020-11-16 13:17 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
>                      relative_dir = os.path.dirname(d_content.content.relative_path)
Done.

2020-11-16 13:18 UTC, ThikaXer commented on pulp_deb/app/serializers/remote_serializers.py
> +        'Set this flag to allow the synchronization of such "partial mirrors" '
Done.

2020-11-16 13:23 UTC, quba42 commented on pulp_deb/app/serializers/remote_serializers.py
> +        help_text="By default, upstream repositories that declare architectures "
Ok, I just remembered local builds of the API docs don't actually work...
I guess we will just have to double check this post release. (At least I don't know of any better way to go about it.)

2020-11-16 13:28 UTC, quba42 approved these changes

2020-11-16 13:37 UTC, mdellweg commented on pulp_deb/app/serializers/remote_serializers.py
> +        'Set this flag to allow the synchronization of such "partial mirrors" '
Yeah it's kind of obvious. If it weren't a boolean it would be called a parameter, not a flag.

2020-11-16 13:42 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +        # Skip if empty packages files
This comment should probably move one line down.

2020-11-16 13:45 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +        # Skip if empty packages files
Or maybe just removed? Not sure it still adds a lot of information in addition to:
```
https://github.com/pulp/pulp_deb/pull/226#discussion_r524229981
    return
```

2020-11-16 13:46 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +        # Skip if empty packages files
In fact I think the "*empty* packages file" still refers to an earlier version of the PR.

2020-11-16 13:50 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +        # Skip if empty packages files
Yes, the code explains itself. (At least to the interpreter, and comments in general tend to be out of sync with the actual code, so don't add unnecessary ones.)

2020-11-16 14:17 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +        # Skip if empty packages files
Comment removed :)

2020-11-16 14:27 UTC, ThikaXer commented on pulp_deb/app/tasks/synchronizing.py
> +                        continue
Maybe something like this?
https://github.com/pulp/pulpcore/pull/1028

2020-11-16 14:55 UTC, merged

2020-11-16 14:58 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +                        continue
Thanks for following up on this.