Moves version to PulpPluginAppConfig
pulp/pulp_deb pull request #240
Opened 2020-12-15 13:53 UTC by mdellweg

This redeploys the plugin template and updates a few files that should
be updated to match but are not plugin template managed.  Specifically:

* Removing `__version__` from `pulp_deb/__init__.py`
* Adding the version string directly to `docs/conf.py`
* Adding the `version` attribute to `PulpPluginAppConfig` subclass in
`pulp_deb/app/__init__.py`.
* Updating .bumpversion.cfg

[noissue]

2020-12-15 16:12 UTC, ipanova approved these changes

2020-12-18 11:36 UTC, quba42 commented
Just for reference, I understand this addresses: https://www.redhat.com/archives/pulp-dev/2020-December/msg00011.html

2020-12-18 11:52 UTC, quba42 requested changes
Since I don't know the exact point in the plugin template that was applied, I am having a little trouble sorting out manual changes from the plugin template. However, comparing with https://github.com/pulp/pulp_file/pull/451/files, and given @ipanova's approval and the green tests I am happy to merge. Thanks for taking this off my hands!

My only requested change is that we not add the empty `HISTORY.rst` file from the plugin template.

2020-12-18 11:52 UTC, quba42 commented on pyproject.toml
> +    "HISTORY.rst",
```suggestion
```

2020-12-18 11:52 UTC, quba42 commented on docs/changes.rst
> +.. include:: ../HISTORY.rst
```suggestion
```
I have only one request, can we not include this empty `HISTORY.rst` file? (Note I can't leave a comment on the file itself, since it is empty).
I guess it comes from the plugin template, but what is it even intended for?
Are any plugins using it? (If not I could open a PR to remove it from the template as well...)

2020-12-18 12:44 UTC, mdellweg commented
@quba42 removed HISTORY.rst.
I have no idea what its detailed purpose was.

2020-12-18 13:02 UTC, quba42 approved these changes

2020-12-18 13:02 UTC, merged