Pulpcore 3.13 compatibility changes
pulp/pulp_deb pull request #273
Opened 2021-04-20 21:38 UTC by dralley

[noissue]

2021-04-20 21:56 UTC, dralley commented
@quba42

2021-04-20 22:03 UTC, dralley commented
These are all of the changes that I know about, but I didn't run the test suite to see if any warnings got printed.

I don't really have time to make the auto-publish and auto-distribute, changes, but the RPM plugin is a good reference.  The old PR isn't useful anymore because we changed course about the way it should be done.  Luckily the new way is much simpler.

2021-04-21 08:02 UTC, mdellweg reviewed
Codewise this looks good. Still should be tested with real data.

2021-04-21 08:23 UTC, quba42 commented on pulp_deb/app/models/repository.py
> +        super().on_new_version(version)
Wouldn't it inherit that function from `super()` anyway, even without adding this code?
I feel like I am missing something basic and obvious here...

2021-04-21 08:38 UTC, quba42 commented on pulp_deb/app/serializers/publication_serializers.py
> +        allow_null=True,
Does this mean I can create a distribution that does not serve anything?

2021-04-21 08:39 UTC, mdellweg commented on pulp_deb/app/models/repository.py
> +        super().on_new_version(version)
Yes, that it what i tried to say. You would extend this function to trigger auto publishing from every newly created version.

2021-04-21 08:41 UTC, mdellweg commented on pulp_deb/app/serializers/publication_serializers.py
> +        allow_null=True,
As a placeholder? I believe yes. It still reserves the basepath on the content app.

2021-04-21 08:53 UTC, quba42 commented on pulp_deb/app/migrations/0014_swap_distribution_model.py
> +                ('distribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_aptdistribution', seria
Break this line somehow, maybe? (I am surprised black/flake did not complain.)

2021-04-21 08:56 UTC, quba42 commented on pulp_deb/app/models/repository.py
> +        super().on_new_version(version)
Ahh, so these lines function a bit like a TODO comment.

2021-04-21 09:01 UTC, quba42 commented on pulp_deb/app/serializers/publication_serializers.py
> +        view_name_pattern=r"publications(-.*/.*)?-detail",
Is the `view_name` for publications somehow automatically built from the `TYPE` string? (I don't fully understand what this pattern is trying to match against.)

2021-04-21 09:39 UTC, mdellweg commented on pulp_deb/app/migrations/0014_swap_distribution_model.py
> +                ('distribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_aptdistribution', seria
As migrations are usually autogenerated, they are on the ignorelist of black.

2021-04-21 09:43 UTC, mdellweg commented on pulp_deb/app/serializers/publication_serializers.py
> +        view_name_pattern=r"publications(-.*/.*)?-detail",
It is built by the viewset. I think it is `<Mastermodel.endpoint_name>-<app_label>/<Model.endpoint_name>-<View.action>`.
So you could try: `r"publication-deb/(.*)-detail` here.

2021-04-21 09:44 UTC, mdellweg commented on pulp_deb/app/models/repository.py
> +        super().on_new_version(version)
I would still either remove or comment them.

2021-04-21 12:27 UTC, dralley commented on pulp_deb/app/models/repository.py
> +        super().on_new_version(version)
Yes, it's basically just a placeholder.

2021-04-22 00:04 UTC, dralley commented on pulp_deb/app/serializers/publication_serializers.py
> +        view_name_pattern=r"publications(-.*/.*)?-detail",
I value consistency across plugins more than being specific for this sort of thing.

2021-04-22 08:37 UTC, quba42 commented on pulp_deb/app/models/repository.py
> +        super().on_new_version(version)
I will look into adding the actual feature based on what I find in other plugins.

2021-04-22 08:39 UTC, quba42 commented
@dralley Thanks for providing this. If you don't mind, I am happy to take over this branch going forward.

I want to run some manual testing of the migration (as suggested by @mdellweg) and also add the auto publish feature.
Hopefully I can get that all done soon.

2021-05-03 13:15 UTC, quba42 requested changes
I have now tested this change for existing distributions migrating both up and back down, without apparent issues.

@dralley Can you still add the (cosmetic) suggestions from https://github.com/quba42/pulp_deb/commit/29c844bec16bccd818469b39fcde4927655df17a to your commit, then I will merge this (and work on adding the auto publish feature on a new PR on top).

2021-05-03 13:19 UTC, dralley commented
@quba42 done

2021-05-03 13:20 UTC, quba42 approved these changes

2021-05-03 14:00 UTC, merged