Ignore package fields with corrupt values
pulp/pulp_deb pull request #348
Opened 2021-09-02 09:00 UTC by Manisha15

Fixes #9333
https://pulp.plan.io/issues/9333

2021-09-02 09:19 UTC, Manisha15 commented
Fixes #9333
https://pulp.plan.io/issues/9333

2021-09-02 10:08 UTC, quba42 requested changes
Some ideas.

2021-09-02 10:08 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +                if key == 'installed_size' and not isinstance(args[key], int):
I wonder if it would be more efficient to build the entire `args` dict without considering the special fields first, and then to remove any broken fields after. So have something like the following just before the return:
```
if 'installed_size' in args and not isinstance(args['installed_size'], int):
    del args['installed_size']
```
and so on.

2021-09-02 14:18 UTC, quba42 requested changes
I also just remembered we wanted to add a log warning whenever we drop a field!

2021-09-02 14:18 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        # Delete package fields with corrupt values
```suggestion
        # Delete package fields with values of an incorrect type
```

2021-09-02 14:18 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        del args['installed_size'] if 'installed_size' in args and not isinstance(args['installed_size'], int)
I need to test to be sure, but I think the current logic won't work because at this point all the fields contain strings. If I am right then what we need to test is whether we have a string that can be successfully casted to the type we want. So the strings `"55"` or even `"   55 "` should count as an int, but `"NaN"` or `" 5 5 "` should not. I am guessing anything that can be successfully converted with `int(string_value)` is fine (though I am not sure that is what is being used to cast things to the right type for the DB field in question).

2021-09-02 14:18 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        if 'multi_arch' in args and not isinstance(args['multi_arch'], str):
If I am right about all fields containing strings at this point then we don't need this test:
```suggestion
        if 'multi_arch' in args:
```

2021-09-06 11:44 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        if "installed_size" in args and not args["installed_size"].strip().isdigit():
As far as I can tell this works well. Note that this validation is different from what the Django `IntegerField` type uses. Django simply tries to cast the incoming value to integer using `int()` ([see here](https://github.com/django/django/blob/ca9872905559026af82000e46cde6f7dedc897b6/django/db/models/fields/__init__.py#L1823)).

We could consider aligning our test with Django, by using something like:
```
if "installed_size" in args:
        try:
            int(args["installed_size"])
        except (TypeError, ValueError):
            log.warn(...)
            del args["installed_size"]
```
Not sure what is better.

2021-09-06 12:22 UTC, quba42 requested changes
I think we are getting there. :stuck_out_tongue_winking_eye:

2021-09-06 12:22 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        if "essential" in args and not isinstance(args["essential"], bool):
This currently does not work, since we need to do something similar as for the "multi_arch" field:
```suggestion
        if "essential" in args and args["essential"] not in [ value[1] for value in BOOL_CHOICES ]:
```
Note that `BOOL_CHOICES` will need to be imported since it is not part of the `BasePackage` class (like `MULTIARCH_CHOICES` is).

2021-09-06 12:22 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        if "build_essential" in args and not isinstance(args["build_essential"], bool):
Same problem as with the `essential` field.

2021-09-06 12:22 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +            value[0] for value in BasePackage.MULTIARCH_CHOICES
```suggestion
            value[1] for value in BasePackage.MULTIARCH_CHOICES
```
Comparing with the `BOOL_CHOICES` this is probably more correct even though it does not make a difference for `MULTIARCH_CHOICES`...

2021-09-06 12:22 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +                    args["package"]
I am wondering if we can be more specific for our warnings, something like:
```
allowed_values = [ value[1] for value in BasePackage.MULTIARCH_CHOICES ]
message="Dropping 'Multi-Arch' field from package {}, since the value '{}' is not in the allowed values list '{}'"
log.warn(_(message).format(args["package"], args["multi_arch"], allowed_values))
```
Printing the value that caused the problem really helps with debugging!

2021-09-06 12:27 UTC, Manisha15 commented on pulp_deb/app/serializers/content_serializers.py
> +        if "essential" in args and not isinstance(args["essential"], bool):
Does the args["essential"] already contains the BOOL_CHOICES value or is it still having value from package? If it is from former then it already is boolean but if it from latter then we need to import BOOL_CHOICES.

2021-09-06 13:20 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        if "essential" in args and not isinstance(args["essential"], bool):
`args["essential"]` contains what was read from the `Packages` file using the `python-debian.deb822` library.
In my test it was `args["essential"] = 'yes'` which is a string and not a bool, so the field was dropped despite containing the correct value "yes".

2021-09-06 15:06 UTC, quba42 requested changes
Only very minor suggestions now, once these are in I am happy to merge!

2021-09-06 15:06 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +                         since the value '{}' is of incorrect type."
```suggestion
                        (
                            "Dropping 'Installed-Size' field from '{}', "
                            "since the value '{}' cannot be casted to type 'int'."
                        )
```
This is needed to avoid having indentation make it into the final string, your version resulted in the following warning:
```
pulp_deb.app.serializers.content_serializers:WARNING: Dropping 'Installed-Size' field from code-insiders,                          since the value NaN is of incorrect type.
```

2021-09-06 15:06 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +                       since the value '{}' is not in the allowed values list '{}'"
```suggestion
        message = (
            "Dropping '{}' field from package '{}', "
            "since the value '{}' is not in the allowed values list '{}'"
        )
```

2021-09-06 15:20 UTC, quba42 approved these changes

2021-09-06 15:35 UTC, merged