fix(deb): baseurl serialization for signing_service
pulp/pulp_deb pull request #380
Opened 2021-12-20 13:24 UTC by jschmid1

Signed-off-by: Joshua Schmid <jaiks@posteo.de>

fixes: https://pulp.plan.io/issues/9563

2021-12-21 09:11 UTC, jschmid1 commented
@quba42

2021-12-27 09:32 UTC, quba42 commented
@jschmid1 In order to link this fix with the issue, the Pulp CI will want:

- `closes #9563` in the commit message (not in the first line).
- A file named `CHANGES/9563.bugfix`. This file should contain a changelog entry like:
```
Fixed a bug requiring users to enter a full URL instead of just a ``pulp_href`` when creating an ``AptReleaseSigningService``.
```

2021-12-27 09:35 UTC, quba42 commented
And thanks for going ahead and just opening this PR, I know I was dragging my feet getting this done. :frowning_face:

2021-12-28 09:45 UTC, quba42 commented
@jschmid1 I have now verified/tested the fix (using the following version of the fix): https://github.com/pulp/pulp_deb/commit/f252699f8424451e0303947d86a0f7ccc9e0c387

You can either adjust this PR to match that version, or I can open a new PR and close this one. Either way works for me.

2021-12-28 09:47 UTC, quba42 requested changes
Some suggested and necessary changes, which I have also pushed to this repo here: https://github.com/pulp/pulp_deb/commit/f252699f8424451e0303947d86a0f7ccc9e0c387

2022-01-03 12:10 UTC, ipanova commented on pulp_deb/app/serializers/publication_serializers.py
>      DistributionSerializer,
that's correct. you should import it from `pulpcore.plugin.serializers`

2022-01-10 10:05 UTC, jschmid1 commented on pulp_deb/app/serializers/publication_serializers.py
>      DistributionSerializer,
resolved in b0e94bf61d53ef98df363b5fcf310e1bb0baef2f

2022-01-10 10:06 UTC, jschmid1 commented
> Some suggested and necessary changes, which I have also pushed to this repo here: f252699

thanks, I rebased atop your suggestions.

2022-01-11 15:37 UTC, quba42 commented
I am afraid the reason this did not lint, is because I prematurely switched the issue tracker in the CI.
This should be fixed once https://github.com/pulp/pulp_deb/pull/425 is merged.

2022-01-11 15:37 UTC, quba42 approved these changes

2022-01-11 15:39 UTC, quba42 commented
@jschmid1 Can you rebase this on top of latest `main` branch one more time, now that I have merged #425, so the tests can run?

Once the tests turn green (they should) I will merge.

2022-01-11 15:57 UTC, merged

2022-01-11 15:58 UTC, quba42 commented
Thanks again @jschmid1.

I plan to do a release containing this change shortly (today or tomorrow).