Add advanced copy mechanism in Pulp3
pulp/pulp_deb pull request #381
Opened 2021-12-27 12:00 UTC by Manisha15

Adds Copy mechanism to be used by Katello to copy content in CV filters

2021-12-27 12:38 UTC, quba42 commented
This change needs to add docs here (and possibly elsewhere): https://github.com/pulp/pulp_deb/blob/main/docs/feature_overview.rst

2021-12-27 12:39 UTC, quba42 commented
I guess this closes the following issue: https://pulp.plan.io/issues/7661

2022-02-17 11:23 UTC, quba42 requested changes
Most of the requested changes are small nitpicks in docstring wording or naming.
I would make one substantive addition to the `_process_config` function.

Once that is done, this should be very much nearing completion.

2022-02-17 11:23 UTC, quba42 commented on pulp_deb/app/tasks/copy.py
> +            content_to_copy = source_repo_version.content.filter(content_filter)
At this point, `content_filter` is just based on the list of `pulp_href` supplied by the user. This list can include href for packages, but also href for metadata types. I have done some testing (by including silly content in the copy on purpose), and so far have not found any errors resulting from this. It does however result in nonsensical content ending up in the target repo, which could cause god knows what problems down the line. I suggest we should be a bit more opinionated here, and provide some sanity checking and guardrails for the user.

I suggest we try doing this in the `_process_config` function, by simply dropping any content of the wrong type from the users list with a warning if `structured` is set to true.

If this comment is too unclear, let's have a meeting about this.

2022-02-17 14:03 UTC, quba42 commented on pulp_deb/app/serializers/__init__.py
> +from .repository_serializers import AptRepositorySerializer, CopySerializer
We decided to leave it as is.

2022-02-17 14:08 UTC, quba42 commented on CHANGES/396.feature
> +AAdd experimental advanced copy workflow for structured copying.
```suggestion
Added experimental advanced copy API with support for structured copying.
```
Noticed a typo, remembered the convention was for passed tense, and made a minor adjustment. :smile:

2022-02-17 15:33 UTC, Manisha15 commented on pulp_deb/app/serializers/repository_serializers.py
> +            "being copied. This will allow for structured publications of the target repository."
Fixed.

2022-02-17 16:19 UTC, quba42 requested changes
Nearly done!

2022-02-17 16:19 UTC, quba42 commented on pulp_deb/app/tasks/copy.py
> +def find_structured_publish_attributes(content, src_repo_version):
```suggestion
def find_structured_publish_content(content, src_repo_version):
```
Final naming nitpick.

2022-02-17 16:19 UTC, quba42 commented on pulp_deb/app/tasks/copy.py
> +    children = set()
```suggestion
    structured_publish_content = set()
```
If we can update all instances of `children` and `find_structured_publish_attributes` we are done!

2022-02-17 16:19 UTC, quba42 commented on pulp_deb/app/tasks/copy.py
> +            content_to_copy = source_repo_version.content.filter(content_filter)
Seems to work as intended.

2022-02-17 16:45 UTC, quba42 commented
I added some minimal "feature overview" documentation.
A full workflow documentation will not be added until there are pulp-cli-deb commands for this feature, and we find the time to write that documentation.

To that end: https://github.com/pulp/pulp-cli-deb/issues/22

2022-02-17 16:59 UTC, merged