Convert CharField to TextField
pulp/pulp_deb pull request #534
Opened 2022-06-01 13:29 UTC by hstct

closes #532

2022-06-02 08:14 UTC, mdellweg commented on pulp_deb/app/models/content.py
> +    sha256 = models.TextField(null=False)
I know, it's hard to keep up, but for checksum fields, we decided that the length is known exactly, so we do not expect this field to change.

2022-06-02 08:14 UTC, mdellweg commented on pulp_deb/app/models/content.py
> +    sha256 = models.TextField()
Same here

2022-06-02 08:14 UTC, mdellweg commented on pulp_deb/app/models/content.py
> +    sha256 = models.TextField()
here

2022-06-02 08:14 UTC, mdellweg commented on pulp_deb/app/models/content.py
> +    sha256 = models.TextField()
and here.

2022-06-02 08:40 UTC, hstct commented on pulp_deb/app/models/content.py
> +    sha256 = models.TextField(null=False)
Thanks for clarifying I missed that. I will revert the change for the checksum fields.

2022-06-02 09:02 UTC, mdellweg approved these changes
LGTM

2022-06-07 07:54 UTC, quba42 requested changes
Everything else LGTM.

2022-06-07 07:54 UTC, quba42 commented on pulp_deb/app/migrations/0018_auto_20220601_1254.py
> +# Generated by Django 3.2.13 on 2022-06-01 12:54
Can we rename the auto-generated migration file to something more meaningful?

See the corresponding change in pulp_rpm as a reference: https://github.com/pulp/pulp_rpm/pull/2515/files

2022-06-13 07:27 UTC, quba42 commented
The failed tests appear to be related to https://github.com/pulp/pulp_deb/pull/541.

2022-06-13 09:03 UTC, quba42 approved these changes
Rebase to let the tests go green, then this is good to merge.

2022-06-13 10:20 UTC, merged