Add optimize mode for sync tasks
pulp/pulp_deb pull request #570
Opened 2022-07-04 07:45 UTC by hstct

This will change the default behavior of synchronize to always use optimize unless it is explicitly set to False.

closes #564

2022-07-04 14:06 UTC, quba42 commented
I would adjust the structure of `last_sync_details` somewhat as follows:
```
last_sync_details:
  remote_options:
    distributions: "<value>"
    components: "<value>"
    architectures: "<value>"
    download_policy: "<value>"
  <distribution>:
    artifact_set_sha256: "<value>"
    <component>:
      <architecture>:
        artifact_set_sha256: "<value>"
```
Remote options belong on the top level, since they are the same for all distributions.
We also need to make sure download_policy is one of the remote options we check.
Rather than having a list of (relative_path, package_index_artifact_set_sha256) tuples we could just make the comonents and architectures nested dict keys just like the distribution. This is mostly a preference thing, and should not ultimately make much of a difference. (The relative_path, can be generated from the component and the architecture, so this contains essentially the same information).

2022-07-07 07:59 UTC, mdellweg commented
Let me just add another thought here. Can we not add information to the repository-version itself how it was made? This would be immutable and the repository can always look at it's latest version to retrieve the thing you are implementing here.

2022-07-11 13:52 UTC, quba42 requested changes
Most of my suggestions just reflect small style changes.
Overall this looks pretty good to me.
There are still some details where I added a reminder to double check things.

The big question is whether we want to go ahead with the `repository.last_sync_details` design, or if we want to rework to use something like `repo_version.creation_details` instead. Unfortunately it does not make sense to punt down the road by accepting the implementation we have and then "maybe adjusting it later", since we should get these model changes right from the get go.

2022-07-11 13:52 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +        self.repository = repository
Might be enough to just save the last_sync_details here?
```
self.last_sync_details = repository.last_sync_details
```
I don't think we are using anything else from the repository and this would make the dict accesses shorter/more readable.

2022-07-11 13:52 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +        self.repository = repository
Never mind we _are_ using the repository to set things for next time...

2022-07-11 13:52 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +                ):
The entire condition could go in a single level as follows:
```suggestion
        if (
            self.optimize
            and distribution in self.repository.last_sync_details
            and not self._has_remote_changed()
            and self.repository.last_sync_details[distribution]["artifact_set_sha256"]
            == release_file.artifact_set_sha256
        ):
```

2022-07-11 13:52 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +            }
This looks like another argument for saving these dicts on the repository version. In that case we are always building a new dict, and never overwriting an existing one, so we would not need to go through these contortions and have something that is hopefully a lot less error prone...

2022-07-11 13:52 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +        component = release_component.component
Reminder to myself: Double check if we should use `.component` or `.plain_component` here!

2022-07-19 12:35 UTC, mdellweg commented on pulp_deb/app/models/repository.py
> +    sync_details = models.JSONField(default=dict)
Can we maybe not subclass this and add some extra_data field on the base class?

2022-07-19 12:36 UTC, mdellweg commented on pulp_deb/app/tasks/synchronizing.py
> +    repository = AptRepository.objects.get(pk=repository_pk)
I guess, you are right for calling the correct `finalize_repository_version` method on it.

So does this fix an existing bug here?

2022-07-21 08:07 UTC, quba42 commented on pulp_deb/app/models/repository.py
> +    sync_details = models.JSONField(default=dict)
It does look a lot like there is no acceptable way to do this just on the plugin side. We will trial adding the field on the pulpcore side. If that works, we will open a pulpcore issue and PR, if not, we are back to the pulp_rpm design of saving the information on the repository in a mutable fashion. :wink:

2022-07-22 15:05 UTC, hstct commented
The current version relies on https://github.com/pulp/pulpcore/pull/2999 to be merged before the tests can pass.

2022-07-23 08:08 UTC, mdellweg commented on pulp_deb/app/models/repository.py
> +    sync_details = models.JSONField(default=dict)
Yes, a pulpcore addition is what i had in mind.

2022-08-02 13:42 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +    repository = AptRepository.objects.get(pk=repository_pk)
I am not aware it previously caused a problem, but it does strike me as better to change it.

2022-08-02 14:12 UTC, quba42 commented
The latest version of this PR, exclusively stores remote options on the new RepositoryVersion field from pulpcore.
The needed `artifact_set_sha256` comparison values are instead queried from the content in the previous repository version (this information has always been present there).

We have successfully tested skipping entire Release files as well as individual package indices. As such this change is now mostly ready for final review.

2022-08-08 15:01 UTC, quba42 approved these changes
I now approve these changes, but since I have been more involved in the latest version as an author, I will look for another secondary review amongst my colleagues. :wink:

2022-08-18 09:00 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +    def _nested_defaultdict(self, existing=None, **kwargs):
We probably don't need this anymore!

2022-08-18 09:10 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +    )
Also re-add InstallerFileIndexes!

2022-08-18 12:10 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +            "policy": self.remote.policy,
For the remote options we should add the following fields:
```
sync_sources
sync_udebs
sync_installer
gpgkey
ignore_missing_package_indices
```

Finally, not a remote option, but if the value for `mirror` sync policy has changed, we also need to do a full sync!

2022-08-18 12:27 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +    def _nested_defaultdict(self, existing=None, **kwargs):
Wasn't being called anymore, removed.

2022-08-18 13:41 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +            "policy": self.remote.policy,
Done.

2022-08-18 13:42 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +    )
Done.

2022-08-18 14:13 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +            "optimize": optimize,
Not actually needed but possibly interesting information for debugging purposes.

2022-08-22 09:34 UTC, quba42 commented
After final internal review/debate, we have decided to merge the current state of this new feature (once the tests turn green).

2022-08-22 09:52 UTC, merged

2022-09-01 07:52 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +    repository = AptRepository.objects.get(pk=repository_pk)
This ended up revealing a previously masked problem with our sanity checks.
We fixed it again using: https://github.com/pulp/pulp_deb/pull/633