Add structured repo docs
pulp/pulp_deb pull request #586
Opened 2022-07-15 12:22 UTC by daviddavis

The script in the docs will be tested by the CI:

https://github.com/pulp/pulp_deb/blob/0429dddf355f7917b047b2696fc15148c641cc8e/.github/workflows/scripts/script.sh#L20
https://github.com/pulp/pulp_deb/blob/0429dddf355f7917b047b2696fc15148c641cc8e/.github/workflows/scripts/script.sh#L41-L43

2022-07-20 07:36 UTC, hstct reviewed
If we can add an expected output this looks good to me.

2022-07-20 07:39 UTC, hstct commented on docs/_scripts/setup.sh
> +export BASE_ADDR=${BASE_ADDR:-http://localhost:24817}
The current documentation doesn't define the hostname:
```
export BASE_ADDR=http://<hostname>:24817
```

However this is probably fine as is I just added this as a note rather than a suggestion.

2022-07-20 11:28 UTC, daviddavis commented on docs/_scripts/structured_repo.sh
> +http --check-status ${CONTENT_ADDR}/myrepo/dists/mydist/mycomp/binary-ppc64/
Added to structured_repo.rst.

2022-07-20 11:28 UTC, daviddavis commented on docs/_scripts/setup.sh
> +export BASE_ADDR=${BASE_ADDR:-http://localhost:24817}
This code is being run by the CI (see post_docs_test.sh) whereas the commands from the other pulp_deb workflow docs aren't. I don't think `export BASE_ADDR=http://<hostname>:24817` is valid bash.

2022-07-20 13:47 UTC, quba42 requested changes
Since a full rework of the existing docs won't happen any time soon, and this PR brings an obvious benefit (docs for a workflow that was previously undocumented), I am not too worried about making the style perfectly consistent with the existing docs.

Since @hstct says he tried out the workflow and it worked, I say we merge. Perhaps after my nitpick with the change note is resolved :smile:.

Thanks a ton @daviddavis for providing these docs, and @hstct for the initial review!

2022-07-20 13:47 UTC, quba42 commented on CHANGES/586.docs
> +Adding structured repo workflow docs.
```suggestion
Added workflow docs on manually creating structured repos.
```
I am hoping this will make clearer that we are talking about structured repos not created via sync.

2022-07-20 13:47 UTC, quba42 commented on docs/_scripts/setup.sh
> +export BASE_ADDR=${BASE_ADDR:-http://localhost:24817}
No, in the past we have not made the CI run any docs workflows.
In general, everything that is there already, is due for a rework.

2022-07-20 14:22 UTC, mdellweg commented on CHANGES/586.docs
> +Adding structured repo workflow docs.
It also makes it clearer that it's not the docs being structured. ;)

2022-07-20 19:32 UTC, hstct approved these changes

2022-07-21 11:19 UTC, quba42 approved these changes

2022-07-21 11:20 UTC, merged