Improve documentation on metadata signing
pulp/pulp_deb pull request #643
Opened 2022-09-16 21:25 UTC by sdherr

The previous documentation was brief to the point of being opaque. This should at least help people get started until more thorough workflow documentation is available.

2022-10-18 15:24 UTC, quba42 requested changes
Found one typo below.

I would also quite like to add a changelog entry for this change. To facilitate this, I have created an issue to go with this PR: https://github.com/pulp/pulp_deb/issues/660

The commit message for this change should now be amended as follows:
```
Improve documentation on metadata signing

closes #660
```

You will also need to add a file named `CHANGES/660.doc` containing the changelog message, perhaps something like:
```
Improved the documentation on metadata signing.
```

Once you make these changes and rebase to latest `main` branch, the tests should turn green.
If you prefer, I can adopt this PR and make these changes myself.

Thanks for this documentation improvement. Especially the `pulpcore-manager add-signing-service` example will help people a lot.

2022-10-18 15:24 UTC, quba42 commented on docs/feature_overview.rst
> +   2. Accept one arg that is the location of the unsigned fine.
```suggestion
   2. Accept one arg that is the location of the unsigned file.
```

2022-11-09 21:52 UTC, sdherr commented
Thanks, I have made the requested changes.

2022-11-10 10:27 UTC, mdellweg approved these changes

2022-11-14 14:22 UTC, hstct approved these changes

2022-11-14 15:54 UTC, quba42 approved these changes
Thanks for the changelog entry!

2022-11-14 16:03 UTC, merged