Add origin and label fields to releases
pulp/pulp_deb pull request #656
Opened 2022-10-14 20:31 UTC by daviddavis

Also create a `PRESERVE_EXTRA_RELEASE_FIELDS` setting that will set these fields during sync. Defaults to False to preserve backwards compatibility.

2022-10-17 11:28 UTC, daviddavis commented
@quba42 can you give this a review before I add some tests?

2022-10-17 12:52 UTC, daviddavis commented
Test commands:

```
pulp deb remote create --name complex-dists --url https://fixtures.pulpproject.org/debian-complex-dists/ --distribution ragnarok/updates
pulp deb repository create --name complex-dists --remote complex-dists
pulp deb distribution create --name complex-dists --base-path complex --repository complex-dists
pulp deb repository sync --name complex-dists
pulp deb publication create --repository complex-dists --structured
http :24816/pulp/content/complex/dists/ragnarok/updates/Release
```

For the release file, Origin and Description are now populated from [upstream](https://fixtures.pulpproject.org/debian-complex-dists/dists/ragnarok/updates/). If you have `PUBLISH_RELEASE_FILE_LABEL` and `PUBLISH_RELEASE_FILE_VERSION` set to `True`, those fields are also populated.

2022-10-18 14:20 UTC, quba42 commented
I understand the desire for this feature. It very much solves a real shortcoming of pulp_deb.

This does touch on a [fundamental design challenge we have](https://github.com/pulp/pulp_deb/issues/599), with how the `Release` model, the `ReleaseFile` model, verbatim publications and APT publications interact with each other and to what extent the information they contain is movable between repositories. Because of this, I need to put some real thought and discussion time into how to move forward with this, so I cannot promise a very quick review and merge here. We are overdue for a new pulp_deb Y-release which will have to happen first.

This contribution certainly helps structure the debate around the above mentioned design challenge but I can't be sure when I will find the time to really dive into it.

2022-10-19 07:41 UTC, quba42 commented
@daviddavis These both sound like reasonable requirements to me for this to become a fully flexible feature covering all possible use cases.

The thing I need to decide, is if it is ok for any newly required fields to live on the `Release` model. Because of #599 I was considering renaming the `Release` model to `Distribution` and having `distribution` be the only field on it. However, I am starting to think, it might be better to make `Distribution` an entirely new model that links up with exactly one existing `Release` model. This might allow us to go ahead with your proposed changes from this PR. I do need to think about that some more.

2022-10-19 10:47 UTC, daviddavis commented
@quba42 sounds good. I’d be happy to help out with the design if you ever need user feedback.

2022-10-26 11:54 UTC, daviddavis commented
There's a problem with the db design here: the fields are nullable which cause problems with unique constraints in postgres ("[Null values are not considered equal](https://www.postgresql.org/docs/current/indexes-unique.html)"). 

So I can make the fields non-nullable and default to empty string. But then I think users will still hit an error after they upgrade and try to re-sync: "Cannot create the new repository version, since it contains multiple Release content with the same distribution...". This is because their old releases will have blank values for label, version, etc while the new releases that get created after this change will have label, version, etc populated which will cause a duplicate conflict.

So I can either make these fields blank and introduce some settings like `PRESERVE_LABEL_FIELD`, `PRESERVE_VERSION_FIELD`, etc that will decide whether or not to populate the field when doing a sync. As long as these settings are false, I think this change will be backwards compatible.

Another option I thought of is to not store these fields on the Release. But rather store them on another model such as Repository. This has the added benefit of not creating multiple Releases for the same distribution/codename/suite when only the fields like label, version, etc differ. However, this seems a bit antithetical to how things are normally handled in Pulp.

Any thoughts?

2022-11-17 18:12 UTC, quba42 commented
@daviddavis I think it might be possible to side step the DB design issues around the `Release` model and still move along with this feature. The idea goes as follows. What if we only added these fields on the `ReleaseFile` model for now.

Syncing would fill the fields using the values from the upstream release file, covering that use case. If users wanted to set there own values they could add an artifactless `ReleaseFile` content to the repo (for the relevant distribution) with the fields set to whatever the user likes. Adding some `ReleaseFile` to a repo version with distribution A would automatically remove all existing `ReleaseFile` content with distribution A before saving the new repo version. (We already do this for syncs). => This should cover all use cases without changing the "problematic" `Release` model.

This would represent an expansion in the scope of the `ReleaseFile` type, which may require some thinking about how this might impact verbatim publications (which are currently the only ones using this type).

Does the basic idea make sense to you, or do I need to explain it better?

2023-01-26 14:02 UTC, daviddavis commented
@quba42 thanks for the response. I'm new to the ReleaseFile model so am trying to understand them. I tried working through a workflow and came up with some questions. To give some background we have deb repos that receive packages in two ways:
1. Additive syncs from our legacy system
2. Users upload deb packages and add them to repos

I tried working working through the second scenario. Luckily, it seems that ReleaseFile has fields origin, label, and description already. First, when I tried to create one, I got an error about artifacts being null so I just set it to an empty dict, which seemed to work:

```
http :8080/pulp/api/v3/content/deb/release_files/ codename="bionic" description="Generated by david" label="debtest bionic" origin="debtest bionic" distribution="bionic" artifacts:="{}"
```

Then I performed the following:

1. I created a Repository, a Release, a ReleaseArchitecture, and a ReleaseComponent.
2. I uploaded a Package, created a PackageReleaseComponent, and added both to the repo.
4. I then added my ReleaseFile to my repo
5. Created a verbatim publication (is this correct? normally we create a structured apt publication)
6. Created a distribution and attached the verbatim publication.

It looks like when I examine the repo via curl, my package is there but the release files, etc are missing. There is no `distss` folder, only a `pool` folder. Did I do something wrong or is there some sort of change in Pulp that needs to be made?

Also, I'm wondering what implications switching to a verbatim publication will have for us given that we do additive syncs and allow users to add packages to repos?

2023-03-08 16:36 UTC, tjmullicani commented
It looks like the 0020_XXX migration id was taken by https://github.com/pulp/pulp_deb/pull/731. Applying this patch now gives the following error:
```console
[root@machine ~]# /usr/local/lib/pulp/bin/pulpcore-manager migrate --no-input
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0020_add_release_fields, 0020_remove_fk_relations_in_packageindex_and_installerfileindex in deb).
To fix them run 'python manage.py makemigrations --merge'
```

2023-03-09 14:45 UTC, daviddavis commented
@tjmullicani thanks. I am looking at redesigning the models based on @quba42's comment. Once I have a design, I'll update the migration and rebase it.

2023-03-13 13:30 UTC, daviddavis commented
@quba42 I spent some time looking at the design and supporting users who will be upgrading. I think there's perhaps a bigger issue: when users upgrade, these fields will begin to populate after they re-sync their repos and they'll encounter a nasty error when they run apt:

```
E: Repository ‘http://dl.google.com/linux/chrome-remote-desktop/deb stable Release’ changed its ‘Origin’ value from ‘Google, Inc.’ to ‘Google LLC’
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

I think we'll want to avoid this. One option would be to only ever sync distribution/codename/suite from upstream but still allow users to populate these extra release fields (origin, label, etc) when creating releases through the api. Another option would be to perhaps introduce a new setting (perhaps `SYNC_EXTRA_RELEASE_FIELDS`, default to False) that prevents population of fields other than distribution/codename/suite when syncing. Changing the setting to True would sync origin, label, etc.

If we go either of these routes, then I don't think it really matters where we store these fields. The fields would be empty for existing Releases and syncing wouldn't change that since for users upgrading, the sync code would only populate distribution/codename/suite. This would have the added benefit of allowing us to place these fields on Release which makes it easier for users creating Releases--they would not have to create two models (Release + ReleaseFile) when setting origin, label, etc.

2023-04-12 07:06 UTC, quba42 commented
> I think we'll want to avoid this. The only option I can think of would be to introduce a new setting (perhaps `SYNC_EXTRA_RELEASE_FIELDS`, default to False) that prevents population of fields other than distribution/codename/suite when syncing. Changing the setting to True would sync origin, label, etc.

I think this makes sense. Needing to take an action on all your APT clients because you updated pulp_deb and re-synced your repos is not a good experience!

One possible tweak to your proposed solution: Should we phase in the new behaviour by having new repos i.e. (repos that do not yet have any repo versions in them) ignore the setting? That way, new repos use all the new features, while old repos do not change their behaviour unless users opt in by changing the `SYNC_EXTRA_RELEASE_FIELDS` setting. What do you think?

2023-04-12 07:15 UTC, quba42 commented
@daviddavis I wanted to alert you that I am nearly done with https://github.com/pulp/pulp_deb/pull/741. (I still need to tweak the DB migration, so it works in both directions, but apart from that, I don't anticipate major code changes to the PR.)

I would like to merge #741 first, so that your PR benefits from this re-structuring of the colliding Release problem as soon as it is in. This will most likely cause some merge conflicts when you rebase your PR on top, but I think they should be fairly straightforward to resolve.

My point is, that now is your chance to have a look at #741 *before* it goes in, and register any concerns you might have.

Once my PR is merged, and yours is re-based, I would like to move quickly to final review and merge of your PR, while my memory of working on this area is still fresh. :wink:

2023-04-12 12:03 UTC, daviddavis commented
> One possible tweak to your proposed solution: Should we phase in the new behaviour by having new repos i.e. (repos that do not yet have any repo versions in them) ignore the setting? That way, new repos use all the new features, while old repos do not change their behaviour unless users opt in by changing the SYNC_EXTRA_RELEASE_FIELDS setting. What do you think?

I think this is a good idea. What I am imagining is that we could add a field (sync_extra_release_fields) to remotes that would default to True. However, for existing remotes, it would be False. Thus all new remotes would automatically start to sync the new fields. Wdyt?

2023-04-12 15:08 UTC, quba42 commented
> I think this is a good idea. What I am imagining is that we could add a field (sync_extra_release_fields) to remotes that would default to True. However, for existing remotes, it would be False. Thus all new remotes would automatically start to sync the new fields. Wdyt?

Yes, that makes sense which behaviour should be used for what needs to be recorded somewhere and the only places I can think of is remote or repository. Of these remote makes more sense, because we are answering the question if certain fields should or should not be synced *from the remote repository*.

2023-05-09 16:01 UTC, quba42 reviewed
I have not quite finished with my review, but I wanted to post what I had. I will continue with this tomorrow.

2023-05-10 12:04 UTC, quba42 commented on pulp_deb/app/serializers/content_serializers.py
> +        method never gets called.
Thanks for the explanation, makes sense.

2023-05-10 17:11 UTC, daviddavis commented on pulp_deb/app/models/content/verbatim_metadata.py
> +                "description",
Would that lead to a unique constraint violation? If a user were to sync a ReleaseFile with `sync_extra_fields` disabled, then it wouldn't fill out version/origin/etc. If the user then goes to resync with `sync_extra_fields` enabled, then I imagine Pulp will try to save the new ReleaseFile (with version/origin/etc populated) which would produce a uniqueness violation since there's already a ReleaseFile with the same relative_path and artifact_set_sha256.

2023-05-17 12:56 UTC, daviddavis commented
I reviewed your PR and have a question. If we add `sync_extra_release_fields` and set it to True by default, then I think for most (if not all users) new Releases will have all the information set. I don't think users will bother to set `sync_extra_release_fields` to False. So I imagine only old Releases will not have these fields set. If the problem is old Releases not having these fields set, then I am not sure how moving the option to Repository will change that unless you somehow go back and update the existing Releases with information from upstream?

2023-06-01 15:17 UTC, quba42 requested changes
As discussed during our [recent meeting](https://hackmd.io/NGGCwV0YQh-ACSiI7koXnA?view) I have a version of this PR on [this branch](https://github.com/ATIX-AG/pulp_deb/tree/fix655-minimal) which does the following:

* rebase to latest main branch and re-generate the migration on top of it.
* Add an [initial revert](https://github.com/pulp/pulp_deb/commit/923fbc148cd1d062869ecda1d85e11da9f700be7) which removes a setting that no longer makes sense (if it ever did) with this new feature.
* [Takes back](https://github.com/pulp/pulp_deb/commit/fc2fac2d85e676c4e8a4259c11ede4fc425f7018) some of the introduced changes, since we want to defer part of them to an immediate follow up PR to be released with this one, and some of them indefinitely/until there is a need.
* Finally there is [a commit that somewhat simplifies the publish logic](https://github.com/pulp/pulp_deb/commit/2344e25e097f7464635920e69091d3c38e66622f). This is intended as a pure refactor/should not change the behaviour.

In my opinion commits two, three, and four [on this branch](https://github.com/pulp/pulp_deb/compare/main...ATIX-AG:pulp_deb:fix655-minimal) should be squashed before merging. The DROP_ME commit should be dropped, leaving two commits to be merged as soon as everyone is agreed the current state works for them.

@daviddavis Feel free to update this PR, or else ping me if there are issues with my commits.

2023-06-01 20:51 UTC, daviddavis commented
@quba42 your changes look good to me. Just to confirm, I should pull in the changes from that branch into this PR and squash them into one commit? I'm also happy to close this PR to let you open a new one if you'd like. Let me know.

2023-06-05 13:06 UTC, quba42 commented
> I'm also happy to close this PR to let you open a new one if you'd like. Let me know.

I decided to go with this option, since I already had the working state branch, and it also allowed me to update the migration one more time (now that #689 was merged).

The replacement PR is here: https://github.com/pulp/pulp_deb/pull/782

2023-06-05 13:06 UTC, closed without merging