Specify and remember the Signing Service that should be used at Repository or Release creation time.
pulp/pulp_deb pull request #689
Opened 2022-11-28 22:20 UTC by sdherr

…itory or Release creation time.

closes #641

2022-11-29 18:17 UTC, sdherr commented on pulp_deb/app/models/repository.py
> +    default_signing_service = models.ForeignKey(
Okay, sure. Done.

2022-12-12 09:20 UTC, mdellweg commented on pulp_deb/app/serializers/repository_serializers.py
> +    )
If you made this a jointable, you could reference the signing service as a related field with `delete=PROTECT` while using `delete=cascade` on the Repository.

You could prevent signing services to be deleted while still referenced.

2022-12-14 22:22 UTC, sdherr commented on pulp_deb/app/serializers/repository_serializers.py
> +    )
Alright, I have just pushed an attempt at that in the latest commit. Let me know if there's a better way that I'm missing. If it looks good I'll squash it down to one commit / db update.

One oddity is that I was unable to figure out how to convert the SigningService model back into a uri, so right now it only returns the uuid pk. If there's something I'm missing there let me know. @daviddavis has filed pulp/pulpcore#3469 to expose the `get_url` method to the plugins so this can be fixed in the future.

2022-12-15 09:19 UTC, mdellweg commented on pulp_deb/app/models/repository.py
> +class AptRepositoryReleaseServiceOverride(BaseModel):
Is this maybe a thing we call `AptRepositoryReleaseOverride` and it's corresponding field on the repository `release_overrides`? Put another way: Will there be more options in the future we may want to override?
I think this should have a `unique_together` on repository and release.

2022-12-15 15:53 UTC, sdherr commented on pulp_deb/app/models/repository.py
> +class AptRepositoryReleaseServiceOverride(BaseModel):
Actually in order to rename the field on the DB model I'd have to rename it on the Serializer too, and that's something I don't want to do. If the DictField on the serializer is named just `release_overrides` then the dict they pass in should probably look something like:
```
"release_overrides": {
    "bionic": {
        "signing_service": "URI",
    },
}
```

Which adds another layer of indirection and makes validating the signing service harder because you can no longer assume that all values getting passed are AptReleaseSigningServices. I would rather not make that change unless there's an actual need.

I have added the unique constraint though.

2022-12-16 11:08 UTC, mdellweg commented on pulp_deb/app/models/repository.py
> +class AptRepositoryReleaseServiceOverride(BaseModel):
You are probably right, i was just looking at the db models and had the impression there was an opportunity. But it's not worth the complexity. Thanks for the explanation.

2023-01-26 14:27 UTC, sdherr commented
@mdellweg ping, I believe this is ready for merging. We have been using this patch without problem for a month now.

2023-01-26 15:36 UTC, mdellweg commented
Can you squash the commits and maybe the migrations too?

2023-01-26 19:07 UTC, sdherr commented
Sure, done, thanks!

2023-01-26 19:39 UTC, sdherr commented
Hmm, we'll I'll try to figure out what the automation is complaining about, but also it occurs to me that we probably update this to use `get_url` now that https://github.com/pulp/pulpcore/pull/3469 is merged.

2023-01-26 19:43 UTC, daviddavis commented on pulp_deb/app/migrations/0020_add_default_signing_services.py
> +                'unique_together': {('repository', 'release_distribution')},
The CI is failing because this constraint is missing from the model.

2023-01-31 20:18 UTC, sdherr commented
I was wrong previously, the version of this PR that we have been running had diverged from this code and there were a couple of things I had to patch up to get it working right. It should be better now though.

2023-03-10 19:42 UTC, sdherr commented
I added some basic tests to exersize this functionality. I don't know why all the github checks are failing; it doesn't seem to be related to my changes and everything works locally here.

2023-03-10 21:52 UTC, hstct commented on pulp_deb/app/migrations/0020_add_default_signing_services.py
> +# Generated by Django 3.2.16 on 2022-11-28 16:56
I believe the tests are failing because the main branch got recently upgraded with a `0020` migration. So probably need to rebase main and adjust the migration order.

2023-03-10 22:11 UTC, sdherr commented on pulp_deb/app/migrations/0020_add_default_signing_services.py
> +# Generated by Django 3.2.16 on 2022-11-28 16:56
Done, thanks!

2023-04-26 21:48 UTC, sdherr commented
An example api workflow setting signing service on a specific release:
```
SIGNING_SERVICE_HREF="/pulp/api/v3/signing-services/77d0ba0f-8d42-4bd5-8818-2707ddcdb11d/

# create the repo, update it to set a signing service override on a release named "signed"
http :8080/pulp/api/v3/repositories/deb/apt/ name=test-repo-signed-release
TEST_REPO_SIGNED_RELEASE="/pulp/api/v3/repositories/deb/apt/699d6531-18e6-48ff-8029-7f0ca6390e49/"
http PATCH :8080$TEST_REPO_SIGNED_RELEASE signing_service_release_overrides:="{\"signed\": \"$SIGNING_SERVICE_HREF\"}"

# create a couple releases
http :8080/pulp/api/v3/content/deb/releases/ codename=signed suite=signed distribution=signed
SIGNED_RELEASE_HREF="/pulp/api/v3/content/deb/releases/1e5ef6b8-bac8-43b0-852a-4d9a8a5ada12/"
http :8080/pulp/api/v3/content/deb/releases/ codename=unsigned suite=unsigned distribution=unsigned
UNSIGNED_RELEASE_HREF="/pulp/api/v3/content/deb/releases/f5ccdb99-47c6-4eb0-b7d1-749b2382dda7/"

# create a couple components
http :8080/pulp/api/v3/content/deb/release_components/ component=main release="$SIGNED_RELEASE_HREF"
SIGNED_COMPONENT_HREF="/pulp/api/v3/content/deb/release_components/8d5e72be-7037-4587-8d40-3d2b545a6870/"
http :8080/pulp/api/v3/content/deb/release_components/ component=main release="$UNSIGNED_RELEASE_HREF"
UNSIGNED_COMPONENT_HREF="/pulp/api/v3/content/deb/release_components/b36535a8-3917-4646-938a-60edcfc70750/"

# add structure content to repo
http :8080${TEST_REPO_SIGNED_RELEASE}modify/ add_content_units:="[\"$SIGNED_RELEASE_HREF\", \"$UNSIGNED_RELEASE_HREF\", \"$SIGNED_COMPONENT_HREF\", \"$UNSIGNED_COMPONENT_HREF\"]"

# distribute and publish it
http :8080/pulp/api/v3/distributions/deb/apt/ base_path=test_repo_signed_release name=test_repo_signed_release repository="$TEST_REPO_SIGNED_RELEASE"
http :8080/pulp/api/v3/publications/deb/apt/ structured:=true repository="$TEST_REPO_SIGNED_RELEASE"

# observe that the "signed" release contains an InRelease file and the "unsigned" release doesn't
```

2023-05-24 16:26 UTC, hstct requested changes

2023-05-24 16:26 UTC, hstct commented on pulp_deb/tests/functional/api/test_publish.py
> +    publication_href = gen_object_with_cleanup(publication_api, publish_data).pulp_href
The `deb_publication_factory` fixture can be used here instead. Debatable if it is really necessary here since we already have `DebAptPublication` imported and also need the `publication_api` for later as well anyway. But then again this would reuse code instead of repeating it.

2023-05-24 16:26 UTC, hstct commented on pulp_deb/tests/functional/api/test_publish.py
> +    repository_api = request.getfixturevalue("apt_repository_api")
Usually we call these fixtures in the function parameters. But I don't mind doing it this way instead. It's actually kinda neat in a way that it could get rid of these test functions with 10+ parameters. :+1:

2023-06-01 15:55 UTC, sdherr commented on pulp_deb/tests/functional/api/test_publish.py
> +    repository_api = request.getfixturevalue("apt_repository_api")
If I remember correctly I did it this way because I needed to specify the cleanup order at the end of the test instead of relying on the pytest default behavior.

2023-06-01 18:18 UTC, sdherr commented on pulp_deb/app/migrations/0022_add_default_signing_services.py
Done. There were some minor updates to the migration required to get it two work on `main`, specifically:

1. The pk is a `pulp_uuid` now, not a generic uuid.
2. The `related_name` on the signing service was unused and needed to be deleted.

2023-06-01 18:19 UTC, sdherr commented on pulp_deb/tests/functional/api/test_publish.py
> +    publication_href = gen_object_with_cleanup(publication_api, publish_data).pulp_href
We discussed on the call that you'd do this after merge if you wished.

2023-06-01 21:42 UTC, hstct approved these changes

2023-06-01 21:44 UTC, hstct commented
LGTM. Will merge this when I get back to work (so probably monday)

2023-06-05 10:40 UTC, quba42 approved these changes
I have not done a full review like @hstct, but had a look over the code and performed the following test workflow:
Set up a signing service:
```
oci-env shell
curl -L https://github.com/pulp/pulp-fixtures/raw/master/common/GPG-PRIVATE-KEY-pulp-qe | gpg --import
echo "6EDF301256480B9B801EBA3D05A5E6DA269D9D98:6:" | gpg --import-ownertrust
SIGNING_SERVICE_NAME='Pulp_QE'
pulpcore-manager add-signing-service --class 'deb:AptReleaseSigningService' "${SIGNING_SERVICE_NAME}" /src/pulp_deb/pulp_deb/tests/functional/sign_deb_release.sh '6EDF301256480B9B801EBA3D05A5E6DA269D9D98'
```
Main workflow using Pulp CLI and http:
```
SIGNING_SERVICE_NAME='Pulp_QE'
ENTITIES_NAME='test'
REMOTE_OPTIONS='--url=https://fixtures.pulpproject.org/debian/ --distribution=ragnarok --distribution=ginnungagap --distribution=nosuite --policy=on_demand'
SIGNING_SERVICE_HREF=$(${PULP_CLI_CMD} signing-service show --name=${SIGNING_SERVICE_NAME} | jq -r .pulp_href)
REMOTE_HREF=$(${PULP_CLI_CMD} deb remote create --name=${ENTITIES_NAME} ${REMOTE_OPTIONS} | jq -r .pulp_href)
${HTTP_CMD} post ${PULP_URL}/pulp/api/v3/repositories/deb/apt/ remote=${REMOTE_HREF} name=${ENTITIES_NAME} signing_service_release_overrides:="{\"ragnarok\": \"$SIGNING_SERVICE_HREF\", \"default\": \"$SIGNING_SERVICE_HREF\"}"
${PULP_CLI_CMD} deb repository sync --name=${ENTITIES_NAME}
APT_PUBLICATION_HREF=$(${PULP_CLI_CMD} deb publication create --simple --structured --repository=${ENTITIES_NAME} | jq -r .pulp_href)
${PULP_CLI_CMD} deb distribution create --name=${ENTITIES_NAME} --base-path=${ENTITIES_NAME} --publication=${APT_PUBLICATION_HREF}
```
This has worked, and I think the PR can be merged as is, I do have a few closing remarks to add:

1. Great job on adding some basic documentation to `docs/feature_overview.rst` and the strings used for the API docs!
2. It looks like adding a `signing_service_release_overrides = {"default": ...` along with `simple=True` on the publication does not interact. I am fine with this, since we want to deprecate usage of `simple=True` anyway. (This is just something to be aware of).
3. We should create an issue at [pulp-cli-deb](https://github.com/pulp/pulp-cli-deb) to add the `signing_service_release_overrides` and `singing_service` parameters to the `pulp deb repository create` command!

2023-06-05 10:40 UTC, quba42 commented on pulp_deb/app/models/__init__.py
> +from .signing_service import AptReleaseSigningService
Just for my understanding: Is moving this from line 29 to 11 _required_ for this to work, or did this "just happen" during development?

2023-06-05 11:00 UTC, hstct commented
> We should create an issue at [pulp-cli-deb](https://github.com/pulp/pulp-cli-deb) to add the signing_service_release_overrides and singing_service parameters to the pulp deb repository create command!

I created the issue: https://github.com/pulp/pulp-cli-deb/issues/54

2023-06-05 11:01 UTC, merged

2023-06-05 13:41 UTC, sdherr commented on pulp_deb/app/models/__init__.py
> +from .signing_service import AptReleaseSigningService
Required, otherwise you hit a circular dependency problem:
```
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/src/pulpcore/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/pulp_deb/pulp_deb/app/models/__init__.py", line 27, in <module>
    from .repository import AptRepository, AptRepositoryReleaseServiceOverride
  File "/src/pulp_deb/pulp_deb/app/models/repository.py", line 5, in <module>
    from pulp_deb.app.models import (
ImportError: cannot import name 'AptReleaseSigningService' from partially initialized module 'pulp_deb.app.models' (most likely due to a circular import) (/src/pulp_deb/pulp_deb/app/models/__init__.py)
```

Python's dependency resolver is only "okay" sometimes.