Improve "No valid Release file found" error message
pulp/pulp_deb pull request #733
Opened 2023-03-09 07:17 UTC by Manisha15

2023-03-09 11:25 UTC, quba42 requested changes
I think we need a small change to the logic, the rest LGTM.

2023-03-09 11:25 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +                    if gpg_verify_count == 0:
I think we need a slightly modified condition here. Something like:
```
if not d_content.d_artifacts:
    if dropped_count > 0:
        raise NoValidGPG(url=self.remote.url)
    else:
        raise NoReleaseFile(url=self.remote.url)
```
where `dropped_count` counts the number of release files we dropped instead of counting the number of release files that successfully verified with `gpg_verify_count`. That way, if the user provides an incorrect URL/distribution, AND also provides a GPG key, they will get the error for incorrect URL/distribution, and not the error for incorrect GPG key. Does that make sense?

2023-03-09 11:25 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +class NoValidGPG(Exception):
Nitpick:
```suggestion
class NoValidSignatureForKey(Exception):
```
I feel like this is a better name, since we don't know if the problem is with the GPG key or with the signature.

2023-03-09 12:20 UTC, Manisha15 commented on pulp_deb/app/tasks/synchronizing.py
> +class NoValidGPG(Exception):
Changed the name.

2023-03-09 12:27 UTC, hstct requested changes

2023-03-09 12:27 UTC, hstct commented on CHANGES/399.feature
> +Improve the pulp_deb "No valid Release file found" error message for gpg validation fail.
According to the issue this a bugfix rather than a feature. I'd personally would mark it as misc. But bugfix is fine as well.

2023-03-09 12:34 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +                            raise NoReleaseFile(url=self.remote.url)
I feel like it would be clearer for users if we used the URL to the affected release file folder here (instead of the URL to the repo root). So we would need to set something like `release_file_folder = os.path.dirname(d_content.d_artifacts[0].relative_path)` and then combine `self.remote.url` with that `release_file_folder`. We might need to watch out in case `d_content.d_artifacts` is the empty list though, so this is a bit messy...

2023-03-09 12:38 UTC, quba42 commented on CHANGES/399.feature
> +Improve the pulp_deb "No valid Release file found" error message for gpg validation fail.
Hmm, I am unsure what it is. Allthough I have heard people say things like: "Unclear documentation/error messages are a bug" so maybe it is a bugfix?

2023-03-09 12:46 UTC, quba42 commented on pulp_deb/app/tasks/synchronizing.py
> +                            raise NoReleaseFile(url=self.remote.url)
I think `d_content.content.relative_path` might also contain the path we want (and avoids the empty list issue). I am not 100% sure though.

2023-03-09 13:21 UTC, hstct commented on CHANGES/399.feature
> +Improve the pulp_deb "No valid Release file found" error message for gpg validation fail.
Bugfix is fine with me :slightly_smiling_face:

2023-03-09 14:29 UTC, hstct approved these changes

2023-03-09 15:05 UTC, Manisha15 commented on CHANGES/399.feature
> +Improve the pulp_deb "No valid Release file found" error message for gpg validation fail.
Changed it to bugfix.

2023-03-13 10:53 UTC, hstct commented
LGTM

2023-03-13 10:53 UTC, merged