Fixed KeyError during publish for unmatched arch
pulp/pulp_deb pull request #778
Opened 2023-05-30 11:40 UTC by daviddavis

When publishing a package that doesn't have a matching architecture in the release component, a KeyError gets thrown. This fixes it so that a warning message is instead logged.

One option would have been to fail the publish with a more user friendly error. However, in our use case, repos are shared across different users/teams so if one team adds a package with an unsupported arch, no one can publish the repo (which is bad). 

In the future, I think it would be good to add some validation to the repo modify endpoint to prevent packages with unsupported architectures from being added to repos.

2023-06-01 15:28 UTC, quba42 commented
This is an obvious improvement on the status quo of "somebody successfully uploaded a package with a new arch, now nobody can publish the repo".

We probably also want to backport this to some existing release branches.

2023-06-05 16:23 UTC, quba42 requested changes
I reproduced the bug (and verified the fix) using:
```
REMOTE_OPTIONS='--url=https://fixtures.pulpproject.org/debian/ --distribution=ragnarok --distribution=ginnungagap --distribution=nosuite --architecture=armeb --policy=on_demand'
ENTITIES_NAME='publish_wrong_arch_test'

${PULP_CLI_CMD} deb remote create --name=${ENTITIES_NAME} ${REMOTE_OPTIONS}
${PULP_CLI_CMD} deb repository create --name=${ENTITIES_NAME} --remote=${ENTITIES_NAME}
${PULP_CLI_CMD} deb repository sync --name=${ENTITIES_NAME}
REPOSITORY_HREF=$(${PULP_CLI_CMD} deb repository show --name=${ENTITIES_NAME} | jq -r .pulp_href)
TASK_HREF=$(${HTTP_CMD} --form post ${PULP_URL}/pulp/api/v3/content/deb/packages/ file@../frigg_1.0_ppc64.deb repository=${REPOSITORY_HREF} | jq -r .task)
${PULP_CLI_CMD} task show --href=${TASK_HREF}

ARCH_HREF=$(${HTTP_CMD} get ${PULP_URL}/pulp/api/v3/content/deb/release_architectures/?architecture='ppc64' | jq -r .results[0])
TASK_HREF=$(${HTTP_CMD} post ${PULP_URL}${REPOSITORY_HREF}modify/ remove_content_units:=[\"${ARCH_HREF}\"] | jq -r .task)
PUBLICATION_HREF=$(${PULP_CLI_CMD} deb publication create --repository=${ENTITIES_NAME} --structured --simple | jq -r '.pulp_href')
```

2023-06-05 16:23 UTC, quba42 commented on pulp_deb/app/tasks/publishing.py
> +                f"that is not available for {self.parent.distribution} ({self.component})."
Clarity nitpick:
```suggestion
                f"Published package '{package.relative_path}' with architecture '{package.architecture}' "
                f"was not added to component '{self.component}' in distribution '{self.parent.distribution}' because it lacks this architecture!"
```

2023-06-06 09:55 UTC, quba42 commented
Reproduced the error and verified the fix for the 2.18 branch. Will add backport tags.

2023-06-06 10:11 UTC, hstct approved these changes

2023-06-06 10:27 UTC, merged