Generating checksum named files for aptbyhash
pulp/pulp_deb pull request #833
Opened 2023-07-13 21:13 UTC by adamsanaglo

2023-07-15 09:21 UTC, daviddavis commented
@adamsanaglo the number of files for this PR seems quite large (84 files). A number of them should be ignored by the .gitignore so I am not sure how you have checked them in. If you run this, it should remove them from git:

```bash
git ls-files -c --ignored --exclude-standard | xargs git rm -r --cached
```

2023-07-15 09:26 UTC, daviddavis commented on pulp_deb/app/constants.py
> +APT_BY_HASH = True
I think this should probably be a setting (see pulp_deb/app/settings.py).

2023-07-15 09:30 UTC, daviddavis commented on CHANGES/795.feature
> +Mitigating the Hash Sum Mismatch error by generating additional metadata files named by checksum
This probably needs some more information for users about the feature and maybe a link to https://wiki.ubuntu.com/AptByHash.

2023-07-15 09:34 UTC, daviddavis commented on pulp_deb/app/tasks/publishing.py
> +                package_hashed_index_path = os.path.join(by_hash_path, _sha256sum(package_index_path))
I think the sha256 will already be available on the artifact for package_index:

```python
package_index.contentartifact_set.first().artifact.sha256
```

2023-07-15 09:37 UTC, daviddavis commented
A couple other things:

* There was a discussion on the issue you filed about how to persist the byhash files across publications. Have you given any thought to that? 
* This probably could use some user docs to at least document the config setting.

2023-07-15 09:39 UTC, daviddavis commented on pulp_deb/app/tasks/publishing.py
> +                package_hashed_index_path = os.path.join(by_hash_path, _sha256sum(package_index_path))
Also, the checksums will probably need to be configurable. And it will likely need to be validated as a subset of [`ALLOWED_CONTENT_CHECKSUMS`](https://github.com/pulp/pulpcore/blob/bbb30b7a5de3cab3ac13e1913facb33f1292e2fe/pulpcore/app/settings.py#L283-L287).

2023-07-15 09:45 UTC, daviddavis commented on pulp_deb/app/tasks/publishing.py
> +    log.info(_("Publication: {publication} createddddd").format(publication=publication.pk))
![image](https://github.com/pulp/pulp_deb/assets/86290/e86480f1-75a4-4636-9fae-64f27065b15c)

2023-07-15 10:14 UTC, adamsanaglo commented
Thank you Mr. Davis.

Best regards,
Adams

On Sat, Jul 15, 2023 at 2:45 AM David Davis ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pulp_deb/app/tasks/publishing.py
> <https://github.com/pulp/pulp_deb/pull/833#discussion_r1264369456>:
>
> > @@ -217,7 +219,7 @@ def publish(repository_version_pk, simple=False, structured=False, signing_servi
>                  for release_helper in release_helpers:
>                      release_helper.save_signed_metadata()
>
> -    log.info(_("Publication: {publication} created").format(publication=publication.pk))
> +    log.info(_("Publication: {publication} createddddd").format(publication=publication.pk))
>
> [image: image]
> <https://user-images.githubusercontent.com/86290/253732703-e86480f1-75a4-4636-9fae-64f27065b15c.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pulp/pulp_deb/pull/833#pullrequestreview-1531328230>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANNTFOTSGWQXN2JICJEGZPDXQJRDVANCNFSM6AAAAAA2JQBAFY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-17 07:56 UTC, mdellweg commented on pulp_deb/app/tasks/publishing.py
> +                package_hashed_index_path = os.path.join(by_hash_path, _sha256sum(package_index_path))
... and sha256 is not allowed to be excluded from `ALLOWED_CONTENT_CHECKSUMS`.

2023-07-17 13:17 UTC, hstct commented
The linting stage needs pass before the actual tests are triggered. Besides the black formatting complain it is very likely that the stage will also complain because the commit message is missing a `closes #795` in the 2nd row of the commit message.

2023-07-17 18:45 UTC, sdherr commented on pulp_deb/app/tasks/publishing.py
> +                package_hashed_index_path = os.path.join(by_hash_path, _sha256sum(package_index_path))
Using `os.path` functions certainly works, but the more modern-python way to do this is to [use pathlib](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module):
```
from pathlib import Path

by_hash_path = Path(package_index_path) / "byhash"
by_hash_path.mkdir(parents=True, exists_ok=True)
package_hashed_index_path = by_hash_path / _sha256sum(package_index_path)
```

2023-07-17 18:50 UTC, sdherr commented on pulp_deb/app/tasks/publishing.py
> +            if APT_BY_HASH:
There's no reason to have the APT_BY_HASH code split into two different if blocks; move the `package_index_path` code above down into this block too. Also there's a lot of duplication between the two, may be a good opportunity to de-duplicate by creating a helper function or wrapping in a loop.

2023-07-17 18:52 UTC, sdherr commented on pulp_deb/app/tasks/publishing.py
>              self.parent.add_metadata(gz_package_index)
[Genuine question] Do you need to add the `package_hashed_index` and `gz_package_hashed_index` here too?

2023-07-17 18:57 UTC, sdherr commented on pulp_deb/app/tasks/publishing.py
> +    h = hashlib.sha256()
FYI if you need to add support for other checksums the more generic way to do this is to call `hashlib.new()`:
```
h = hashlib.new("sha256")
h.update("whatever")
h.hexdigest()
```

2023-07-17 19:29 UTC, daviddavis commented on pulp_deb/app/tasks/publishing.py
> +                )
I looked at [the `create_from_file` method in pulpcore](https://github.com/pulp/pulpcore/blob/f7e62bb03948db8ae230a64d9642d7e144ce02ca/pulpcore/app/models/publication.py#L271) and I think you can just specify the relative_path instead of copying the file. Maybe something like this:

```python
package_hashed_index = PublishedMetadata.create_from_file(
    publication=self.parent.publication,
    file=package_index_path,
    relative_path=f"{package_index_path}/byhash/{package_index.contentartifact_set.first().artifact.sha256}"
)
```

2023-07-17 20:37 UTC, adamsanaglo commented on pulp_deb/app/tasks/publishing.py
>              self.parent.add_metadata(gz_package_index)
I found that by doing so the checksum named files would be added to the InRelease file, which would be cyclical based on this specification:
`A dists/<release>/by-hash/<algorithm>/<hash> URL MUST return the corresponding file for every hash and hash algorithm listed in dists/<release>[/InRelease](https://wiki.ubuntu.com/AptByHash/InRelease) for that file.`

2023-07-19 19:58 UTC, sdherr commented on pulp_deb/app/tasks/publishing.py
> +                gz_package_hashed_index.save()
```suggestion
for path in (package_index_path, gz_package_index_path):
    hashed_index_path = _create_checksum_file(...
    hashed_index = PublishedMetadata...
    hashed_index.save()
```

2023-07-19 20:09 UTC, sdherr commented
> Besides the linting stage: ready-to-ship is complaining because your commit is missing either a `[noissue]` or better a `closes #795` (for the AptByHash issue) in the 2nd row of the commit message. This will not block tests I believe but it needs to happen at some point before the merge :)

The PR Description becomes the commit message when it's merged so he's asking you to fill in the Description and include a `closes #795` to link the two. This is what the `ready-to-ship` check is failing on if you click "details".

2023-07-19 20:10 UTC, sdherr commented on pulp_deb/app/tasks/publishing.py
> +    by_hash_path.mkdir(parents=True, exists_ok=True)
`exist_ok`, singular. This is what the tests are failing on, although it's less obvious because this error message is mixed in with some others that don't look like they can be related to this PR.

2023-07-19 22:15 UTC, hstct commented
> The PR Description becomes the commit message when it's merged so he's asking you to fill in the Description and include a closes #795 to link the two. This is what the ready-to-ship check is failing on if you click "details".

Not exactly. It's the first commit that is missing the link to the issue. Which can be done with squashing all the commits and give it one proper commit message including the `closes #795`. This can be done now and add future commits with an amend commit / force push workflow or squash at the end once the feature is ready.

2023-07-21 11:01 UTC, daviddavis commented on pulp_deb/app/tasks/publishing.py
> +    shutil.copyfile(file_path, hashed_path)
You shouldn't need to copy the file at all if you just specify `relative_path` when creating `PublishedMetadata`. See my comment [here](https://github.com/pulp/pulp_deb/pull/833#discussion_r1265810805).

2023-07-21 11:02 UTC, daviddavis commented on pulp_deb/app/settings.py
> +PUBLISH_RELEASE_FILE_VERSION = False
Are you adding these config variables? I don't see them referenced elsewhere in the PR.

2023-07-21 13:57 UTC, daviddavis commented on pulp_deb/app/tasks/publishing.py
> +    by_hash_path = Path(file_path).parents[0] / "byhash"
I don't thin kthis path is quite right. From the wiki:

> A dists/<release>/by-hash/<algorithm>/<hash> URL MUST return the corresponding file for every hash and hash algorithm listed in dists/<release>[/InRelease](https://wiki.ubuntu.com/AptByHash/InRelease) for that file.

So you need "by-hash" instead of "byhash" and the algorithm type.

2023-07-24 22:17 UTC, adamsanaglo commented on pulp_deb/app/settings.py
> +PUBLISH_RELEASE_FILE_VERSION = False
I left them in during a merge

2023-07-25 20:27 UTC, daviddavis commented on pulp_deb/app/tasks/publishing.py
> +    hashed_path = Path(file_path).parents[0] / "by-hash" / APT_BY_HASH_CHECKSUM_TYPE / h
```suggestion
    hashed_path = Path(file_path).parents[0] / "by-hash" / CHECKSUM_TYPE_MAP[APT_BY_HASH_CHECKSUM_TYPE] / h
```

2023-07-26 11:31 UTC, mdellweg commented on functest_requirements.txt
> +epdb
I don't think this is a test requirement.

2023-08-09 07:26 UTC, hstct commented
I have a few questions regarding this feature and I guess AptByHash in general. As I understand it this PR will only fetch the `/by-hash/` for the components (e.g. `/bullseye/main/binary-amd64/by-hash/`)? Will this be sufficient for utilizing this `apt` feature?

In the issue there is a specification (https://wiki.ubuntu.com/AptByHash) which only mentions the `/by-hash/` of a release - so that's where I'm confused.

I tested the feature branch with various debian repositories and it does fetch the component hashes if they exist on the remote and doesn't if the remote does not provide it.

NOTE: I realized unrelated to this feature that my test environment somehow doesn't sign Releases currently. So I will try to fix that today and have another look at it and maybe it answers some of my questions. I just wanted to give a status update.

2023-08-09 09:36 UTC, daviddavis commented
I was able to test out the feature without signing the release. Here's my Dockerfile:

```
FROM ubuntu:22.04

RUN echo "deb [trusted=yes] http://localhost:24816/pulp/content/test/ mydist mycomp" > /etc/apt/sources.list.d/test.list
RUN apt-get update
RUN apt-get install -y <package name>
```

2023-08-21 06:46 UTC, quba42 requested changes
The below is just a first pass collecting nitpicks (small style improvements that are not that important).

I will collect any feedback about the feature itself in a separate review, but wanted to give you the chance to already fix these nitpicks in the meantime.

In addition to my comments below, I see the following small ToDos:

- [x] Once done with the nitpicks, it would be a good time to squash your commits together into a single commit. Right now there are a lot of intermediary commits that add things that are removed again in a later commit. This does not need to be kept in the history for ever.
- [ ] By convention, commit messages should leave the second line of the commit message blank, so there should be a blank line before the `closes #795` in your final commit message.

2023-08-21 06:46 UTC, quba42 commented on functest_requirements.txt
> +python-debian>=0.1.36
Nitpick: Try to avoid whitespace changes like this (`\ No newline at end of file`). I recommend configuring your editor to add newlines at the end of the file automatically.

2023-08-21 06:46 UTC, quba42 commented on pulp_deb/app/tasks/publishing.py
> +
Nitpick: Try to avoid whitespace changes where nothing else has changed (unless this was done by black?).

2023-08-21 06:46 UTC, quba42 commented on pulp_deb/app/tasks/publishing.py
> +
Same as the previous comment.

2023-08-21 06:46 UTC, quba42 commented on pulp_deb/app/tasks/publishing.py
> +            # Done generating
Nitpick: This comment is not needed. (It does not contain any information not already carried by the indentation).

2023-09-06 10:20 UTC, quba42 commented
It looks like most of my suggestions have been applied on the follow up PR #833 that replaces this one (since the work was taken over by a different developer).

As a result I am closing this PR in favor of #833

2023-09-06 10:20 UTC, closed without merging