Update README badges
pulp/pulp_deb pull request #856
Opened 2023-08-01 07:00 UTC by quba42

[noissue]

2023-08-01 11:33 UTC, hstct requested changes

2023-08-01 11:33 UTC, hstct commented on README.md
>  [7]: https://rubygems.org/gems/pulp_deb_client
It's weird to split the links up like that. Can we just put them all at the bottom?

2023-08-01 12:07 UTC, quba42 commented on README.md
>  [7]: https://rubygems.org/gems/pulp_deb_client
Sure. I guess to be fully consistent, we should probably move the status update badge links into this list at the bottom as well...

2023-08-01 21:45 UTC, hstct approved these changes

2023-08-16 07:10 UTC, quba42 commented
Squished the commits without changing anything.

2023-08-16 07:12 UTC, quba42 commented
Note that this README is also used on [pypi.org](https://pypi.org/project/pulp-deb/).

2023-08-16 09:00 UTC, merged